### ISSUE TITLE
Check translatability of achievements

### ISSUE THREAD

**Issue by Schneegans** [Schneegans/Fly-Pie#102]
The achievements got merged to `develop`. It would be great if someone (@daPhipz?) could try to translate them and provide some feedback. This requires a lot of creativity, most of them cannot translated directly...

_Spoiler Alert: You can use the dconf-Editor for cheating, ... uhm ... testing, I mean :wink:_

**Comment by naDevi** [comment]
Hey @Schneegans 
Can you start to use https://weblate.org/? it's opensource and self-hostable tool but cloud service free for libreprojects https://hosted.weblate.org/hosting/ it's quite difficult to do that locally and there're proprietary platforms similar crowdin, transifex.

**Comment by daPhipz** [comment]
Thanks for the ping!
I am working this weekend, but may find some time here and there. So no promises ;)

**Comment by Schneegans** [comment]
@naDevi: I am kind of hesitant to use online tools because I used Zanata before and the experience was at best mediocre. My main issue was that basically all localizations had to be contributed via Zanata, else there would be massive conflicts.

However, I had a quick look at weblate and it seems to be much better in this regard. It seems to support automatic pull requests on GitHub which would solve the issue I had with Zanata. So thank you for the hint, I will test this!

**Comment by Schneegans** [comment]
Just tested it and the first PR was already created by the Weblate bot :D ... Seems to work quite nicely! I will play around some more. Here's the project:

https://hosted.weblate.org/projects/fly-pie/core/

**Comment by daPhipz** [comment]
So we should contribute translations exclusively over Weblate now, or are direct PRs to the repo still accepted? I'm not against that or anything, just wanted to know the "official" way ;)

**Comment by Schneegans** [comment]
I would like to support both. But we have to test this :). As long as the template is not updated too often, I could work, I guess.

**Comment by daPhipz** [comment]
Ok, i'll use Weblate then. If I have the time, I'll propose an update to the README docs on translating as well.

**Comment by Schneegans** [comment]
In fact, you could try to translate some of the strings with standard offline tools and make a PR and the other half using Weblate. Then we will see what happens :)

**Comment by daPhipz** [comment]
Good idea!

**Comment by Schneegans** [comment]
A difficulty with this approach is definitely that it's more involved for translators to actually test their localization. If you update the translation guide, @daPhipz, it would be great to describe how to test the translation.

Weblate seems to create a PR as soon as someone edits a translation (e.g. https://github.com/Schneegans/Fly-Pie/pull/104) and I would like to encourage translators to checkout the bot's branch (https://github.com/weblate/Fly-Pie/tree/weblate-fly-pie-core) and check how everything looks. Of course this is not necessary if someone 'just' fixes a string here and there but for entirely new translations, this would be a good practice, I guess.

Also, we should add more comments to help translators on their way. If you cannot easily test where the translated strings show up, this becomes even more important.

**Comment by naDevi** [comment]
Thanks^^ @Schneegans
I like online tool because it reduce the fever fall into translator. It helps to track source string modifications, added new strings, provide instant translations to project, multiple translators able to contribute individually and simultaneously etc 
eg: if i maintain 20 projects specific language translations then atlaest every few months i have to check for changes one by one.

>So should we contribute translations exclusively over Weblate now, or are direct PRs to the repo still accepted? I'm not against that or anything, just wanted to know the "official" way ;)

@daPhipz you can upload offline translation directly to weblate then it's like alternative option to PR and it's possible to save translation as suggestion without login to account (but you need to login for direct saving)

**Comment by Schneegans** [comment]
@daPhipz: Maybe you could add this hint to the updated translation guide:

> Most achievements have five tiers. In these cases, you can use a `%i` and / or a `%s` in the achievement's name. In English, `%i` will be replaced by the corresponding roman tier number (I, II, III, ...) and `%s` will be replaced by one of the attributes ('Novice', 'Master', ...). Both of these can be translated as well, so you may get quite creative here :).

I'll add a similar note to the Weblate UI. Currently it's a source code note which is not easy to find in Weblate. So I'll add it there as a manual explanation.

**Comment by Schneegans** [comment]
Fly-Pie just got approved as "libre" project on Weblate!
@daPhipz: If you haven't started on the translation guide update, I'll do this later today. So you can spend your time on the actual translation :)

**Comment by Schneegans** [comment]
I just updated the guide. Feel free to improve it!

https://github.com/Schneegans/Fly-Pie/blob/develop/docs/translating.md

**Comment by daPhipz** [comment]
> Fly-Pie just got approved as "libre" project on Weblate!

Woop woop! 🎉

No, I didn't start yet. Had some veeery busy days at work, so I preferred relaxing over FOSS work in my free time 😓

**Comment by Schneegans** [comment]
Will you guys be able to work on the translations in the coming days? I plan to release Fly-Pie 6 on the 9th of May

@daPhipz, if you do not have the time until then, I can make an initial attempt on the German translation as well!

**Comment by Schneegans** [comment]
@daPhipz: I started working on the German translation via Weblate. Feel free to contribute there if you find the time. But you should not try to use offline tools now, else we'll get severe conflicts :smile:

**Comment by Schneegans** [comment]
@daPhipz: I managed to translate everything and will release Fly-Pie 6 quite soon. Nevertheless, I would really appreciate it if you could look over it at some point as you have more experience with this stuff :D.

**Comment by daPhipz** [comment]
@Schneegans I'm sorry that it took me so long to answer - many things are going on in my life right now and (sadly) FOSS contributions have to take a step back for the foreseeable future.
I will definitely look over the translation some time, but no ETA... I hope you can understand. 🙈😊
