### ISSUE TITLE
Add multi monitor support

### ISSUE THREAD

**Issue by Gregman-js** [Schneegans/Fly-Pie#11]
Hello, first - a great extension, but i have found a bug/feature request
## Describe the Bug
When laptop connected to second monitor, fly-pie can't recognize one window resolution properly.
- menus sometime are not visible when opened in top area of screen smaller screen.
- gray background covers only part of screen. Seems like screen height is calculated from small screen and background is painted starting from bigger screen (Y axis)
sometimes bug looks different

1. Connect second monitor
2. Move cursor to top area of smaller screen
3. Open menu
4. Choose sub-menu above general menu
5. Icons are displayed in not visible area of screen.

## Expected Behavior
I think program should calculate position of mouse on the screen, and get current screen resolution to properly calculate UI area.

## System
 - Fly-Pie version 2
 - Gnome Shell version: 3.36.4
- System: Ubuntu 20.04
### Monitor configuration
Left smaller laptop screen: 1366x768, right bigger monitor 1920x1080
![image](https://user-images.githubusercontent.com/39136587/91987496-6b23ac80-ed2e-11ea-84b2-15fd8111ca5c.png)

**Comment by Schneegans** [comment]
Thank you for the report! Multi-monitor support is definitely on the roadmap. I think it is actually already mentioned as a to-do item in the README.md. Anyways, to implement this, I will have to get an external monitor in the first place. I will update this issue as soon as I can start working on this.

In the meantime - if anybody with a secondary monitor is willing to implement this - go ahead!

**Comment by Schneegans** [comment]
This is now being worked on by @gaamdalurt in #23 . Thank you!
