### ISSUE TITLE
May I re-use some workflow scripts?

### ISSUE THREAD

**Issue by daPhipz** [Schneegans/Fly-Pie#115]
I would like to re-use the scripts that automate the translation workflow for another GNOME Extension: https://github.com/stuarthayhurst/alphabetical-grid-extension.

Is this ok? I would of course leave a comment in the file with links to this repo and its license.

**Comment by Schneegans** [comment]
Of course, it's all MIT :smile:

**Comment by daPhipz** [comment]
Long live FOSS Licenses! Thanks ;)

**Comment by daPhipz** [comment]
https://github.com/stuarthayhurst/alphabetical-grid-extension/pull/3, in case you are interested!
