### ISSUE TITLE
Add Pen Support

### ISSUE THREAD

**Issue by cheeseypi** [Schneegans/Fly-Pie#12]
## The Proposal
This would be fantastic to use with laptops with wacom drivers built-in -- Being able to trigger a menu off of presses from a pen button would be incredible -- It would function much like the s-pen on samsung phones/laptops

The actual menu navigation works decently with a pen, but being able to trigger a menu from the pen buttons would be incredible

**Comment by Schneegans** [comment]
To some degree, this should be possible already.

Can you make the pen buttons simulate hotkeys? Then it would be possible easy, obviously.

With Wayland / Mutter it is currently impossible to globally bind anything to mouse buttons ([background information](https://discourse.gnome.org/t/how-to-bind-modifier-mousebutton-in-gjs/3743)). If you are on X11 however, you could use [XBindKeys](http://www.nongnu.org/xbindkeys/xbindkeys.html) to achieve your goal. With this example configuration

```
"gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/shell/extensions/flypie --method org.gnome.Shell.Extensions.flypie.ShowMenu 'Main Menu'"
  shift+b:2

```

you could open a menu called "Main Menu" by pressing <kbd>Shift</kbd> + <kbd>Right Mouse Button</kbd>.

Does this help you?

**Comment by cheeseypi** [comment]
Ooh good idea, I'll try it out. Thanks!
