### ISSUE TITLE
Multiple hotkeys for the same menu

### ISSUE THREAD

**Issue by cheeseypi** [Schneegans/Fly-Pie#13]
## The Proposal
Add multiple triggers for one menu -- I.e. triggering the same menu from ctrl+space and alt+home or something like that

**Comment by Schneegans** [comment]
Thank you for the idea! Can you describe a situation where this would be helpful? I think it would make the user interface of the settings dialog more cluttered than it is now. I am not sure if that is something many people would require...

As a workaround, you could open your global shortcuts (<kbd>Super</kbd> + Type `Shortcuts`) and add a new one which executes something like

```
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/shell/extensions/flypie --method org.gnome.Shell.Extensions.flypie.ShowMenu 'Main Menu'
```
Just replace `Main Menu` with your menu's name!
What do you think?

**Comment by cheeseypi** [comment]
That would probably work... I'm thinking for people who have multiple workflows, where sometimes their hands are on the home row, sometimes wasd + mouse, and sometimes hand-over-numpad, it might be nice to have a different set of keys launch the same menu. Hotkeys definitely work, but to cut down on clutter in the main interface you could just have a + button on the right directly below the bind block that would allow someone to add additional blocks

**Comment by Schneegans** [comment]
The idea with the + button is actually quite good. I will not implement this right away (there is other stuff to be done) but leave this open for reference. If anyone is interested to implement this - just leave a note here and go ahead!

**Comment by Schneegans** [comment]
I think that this will not be implemented into Fly-Pie. This is mostly because I am currently focusing on the successor project [Kando](https://github.com/kando-menu/kando) and the workaround mentioned above could be sufficient for most use-cases.
