### ISSUE TITLE
Having 2 main menus makes the second one not escape/close

### ISSUE THREAD

**Issue by cindrmon** [Schneegans/Fly-Pie#136]
## Describe the Bug
I was just playing around with fly-pie menu editor, and I figured out that I can do more than 1 main menu (besides the one provided by default). I tried making another menu and tested it out with another shortcut. When I did the shortcut and it works, launching the app doesn't close this second menu, and it is stuck there. I don't know how to close it, and I can't even find the program itself on htop. The only way I was able to get out was to log out (it was a good thing that the second main menu had the system menu on it). I'm not sure if anyone had the same issue as mine, and how they resolved it, but it's there.

1. Launch 'Fly-Pie' Extension Settings
2. Go to 'Menu Editor'
3. Make sure you have already set a 'Main Menu' with its own keybindings.
4. Click on the '+' icon on the upper left.
5. Click 'Custom Menu'
6. Create another main menu beside the first main menu
7. Set the keybinding for the second main menu separate from the main menu. (I currently set the first main menu as `Super`+`D` and the second main menu as `Super`+`E`
8. Attempt to open the second main menu with the set keybinding.
9. Attempt to launch a program from within the second menu.

## Expected Behavior
Fly-Pie will not close at all, even after launching the program or even pressing the `Esc` key, unlike the first main menu.

## System
_Please complete the following information:_
 - Linux distribution [e.g. Ubuntu 20.04]: `Arch Linux 5.14.3-arch1-1`
 - Fly-Pie version [e.g. Fly-Pie 3, or commit SHA]: `Fly-Pie 7`
 - GNOME Shell version: [e.g. 3.36.2]: `40.4`

**Comment by Schneegans** [comment]
Thanks for your report! However, I cannot reproduce this on my end. There are two things we can try:
1. Run `journalctl -f -o cat | grep -E 'flypie|'` in a terminal and then reproduce the behavior. Are there any Fly-Pie-related messages printed?
2. Save and upload your menu configuration from the menu editor. Then I can try to reproduce this with your configuration!

**Comment by cindrmon** [comment]
Good day.

Apparently, it suddenly "fixed" itself, and i am now able to access the second main menu properly without issues.

All I did was restart my pc, and I might've assumed that there might be some issue in the background.

Currently, i can now press `Esc` when accessing the second main menu, and it already closes properly when i launch an application through the second main menu.

Thank you for the concern, and sorry for the inconvenience.
