### ISSUE TITLE
Active shortcut not working on xorg

### ISSUE THREAD

**Issue by FahriDevZ** [Schneegans/Fly-Pie#138]
For wayland it runs normally, but after the change to xorg something happens, I can't use active shortcut.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/22916016/134970307-2e383340-307d-4d24-aff5-62be391040a9.gif)

journalctl -f -o cat | grep -E 'flypie|'
```
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
[xkb] BOGUS LENGTH in SetMap: expected 268 got 1288
```

Fedora 34
GNOME Shell 40.4
fly-pie: version 8

**Comment by Schneegans** [comment]
Thanks for the report! However, I cannot reproduce the issue. I just tested it in a Fedora 34 VM and the menu works fine, both under Wayland X11. I get the same warnings (I also get these on Ubuntu, btw) so I think these are not directly related.

Just to be on the safe side: If you manually press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Arrow</kbd>, the workspace is switched?

Could you test this with other shortcuts, like <kbd>print</kbd>, <kbd>volume up</kbd> or <kbd>Ctrl</kbd>+<kbd>Z</kbd>?

**Comment by FahriDevZ** [comment]
Press manually everything work fine, like <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Arrow</kbd>.
shortcuts <kbd>ctrl</kbd>+<kbd>z</kbd>, <kbd>alt</kbd>+<kbd>1</kbd> in text editor doesn't work, but instead writes `z`, or `1` in text editor, for <kbd>print</kbd> nothing happens.

**Comment by Schneegans** [comment]
That's weird. What shortcut are you using to open the menu?

**Comment by FahriDevZ** [comment]
i  use shortcut <kbd>ctrl</kbd>+<kbd>space</kbd> to open menu

**Comment by FahriDevZ** [comment]
Okay, finally I know this problem. this happens because I didn't use `English (US)` input sources in keyboard gnome setting.
Try use different input source, I am using `Indonesian (latin)`

**Comment by Schneegans** [comment]
That's a good find! I randomly selected the Bosnian input source on my end... and it does not work anymore! Later today I will look into the code. I am pretty sure that this is something in `src/common/InputManipulator.js`...

**Comment by Schneegans** [comment]
Btw, I see that you are already using the git version! If you have some basic JavaScript knowledge, you can also try to find the issue in parallel. There must be a difference in how these modifiers work between Wayland and X11...

You could start by putting `utils.debug("hello world");` anywhere in that file. Then `./scripts/create-release.sh -i`, restart GNOME Shell and observe the output with `journalctl -f -o cat | grep -E 'flypie|'`.

**Comment by Schneegans** [comment]
I just revisited this one and it seems to work now.... I am currently on GNOME 42. Have you tried this once more?
