### ISSUE TITLE
Application window error

### ISSUE THREAD

**Issue by smginroman** [Schneegans/Fly-Pie#14]
## Describe the Bug
![bug]
(https://user-images.githubusercontent.com/60853630/92095104-ed1ede80-eddd-11ea-92fd-832c0eec339e.png)

1. Go to 'Menu structure'
2.Select the emoji  Click on 'backspace' 
3. See error

_Please complete the following information:_
 - Fly-Pie version [2]
 - Gnome Shell version: [3.36.5]

**Comment by Schneegans** [comment]
Thanks for the report! This looks weird. Can you please close the Fly-Pie settings dialog, run `journalctl /usr/bin/gnome-shell -f -o cat | grep flypie -B 2 -A 2` in a terminal (this will later print any error if one occurs) and then reproduce the bug? Maybe something useful is printed to the console!

Other useful information might be your GTK version (`dpkg -l libgtk-3-0`) and the name of your GTK theme.

Thank you!

**Comment by smginroman** [comment]
The output is empty.
![bug term](https://user-images.githubusercontent.com/60853630/92107477-881fb480-edee-11ea-811c-aa0b36f1aa0d.png)
The name of theme is Arc-Dark

**Comment by Schneegans** [comment]
What Linux distribution are you using? Ubuntu 20.04? And I do not really understand what you mean by _"Select the emoji Click on 'backspace'"_. Which emoji?

**Comment by Schneegans** [comment]
I think I found the source of this issue. If you want to, you may try the current develop branch!
