### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by sunnlife1978** [Schneegans/Fly-Pie#15]
Hi, 
I cannot install Fly Pie extension in Fedora 31 and GNOME Shell 3.34.5

Alex

**Comment by Gladox114** [comment]
I can't install it either. Using Pop!_os 20.04 and Gnome 3.36.3
`Error: Requiring GMenu, version none: Typelib file for namespace 'GMenu' (any version) not found

Stack trace:
  @/home/fuyu/.local/share/gnome-shell/extensions/flypie@schneegans.github.com/common/ItemRegistry.js:11:38
  @/home/fuyu/.local/share/gnome-shell/extensions/flypie@schneegans.github.com/settings/MenuEditor.js:17:23
  @/home/fuyu/.local/share/gnome-shell/extensions/flypie@schneegans.github.com/settings/Settings.js:17:23
  @/home/fuyu/.local/share/gnome-shell/extensions/flypie@schneegans.github.com/prefs.js:12:18
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  `

**Comment by Schneegans** [comment]
This looks like you might be missing a gmenu package. Could you try installing something like [this](https://fedora.pkgs.org/31/fedora-x86_64/gnome-menus-3.32.0-2.fc31.x86_64.rpm.html) on Fedora or [this](https://packages.ubuntu.com/xenial/libs/gir1.2-gmenu-3.0) on Pop!_os?

**Comment by Schneegans** [comment]
Does this solve the issue? If so, I would make the main menu submenu an optional feature and check for the existence of this package.

**Comment by Schneegans** [comment]
So we're definitely dealing with two different problems here. On Pop!_os the package `gir1.2-gmenu-3.0` needs to be installed. On Fedora 31 the GNOME Shell version is too old. I have only tested Fly-Pie on 3.36 so far but I may manage to back-port it to GNOME Shell 3.34. On Fedora 32 it seems to run without any issues.

**Comment by Schneegans** [comment]
I just pushed something to `develop` which may fix the GNOME Shell 3.34 issue. It would be great if you could uninstall Fly-Pie (if installed from extensions.gnome.org) and install the latest version from `git`. Here's a guide: https://github.com/Schneegans/Fly-Pie#cloning-the-latest-version-with-git.

**Comment by Schneegans** [comment]
Closing this as it should be fixed. Please re-open or create a new issue if this problem is still existent!
