### ISSUE TITLE
Application-dependent, context-aware menus

### ISSUE THREAD

**Issue by developer91234** [Schneegans/Fly-Pie#153]
(not sure how possible this is under wayland)

## The Motivation
The current menus is a cool addition to the desktop UI. However the desktop UI is already probably the most polished and efficient part of the user's interaction. The application UIs are in much worse shape, in addition to being completely inconsistent. Thus it might be worthwhile to have a flie pie menu that changes depending on which application window is raised. This would allow fly pie to essentially extend the UI of individual applications. As I said, the app UIs are the thing that is in desperate need of optimization.

## The Solution
Enable the user to:
1. Create an empty root menu "context_aware_menu"
2. Draw menu structure "menu_x" if condition x=TRUE.
3. Draw menu structure "menu_y" if condition y=TRUE.
4. etc. Thus you create custom menus for different scenatios.

The most useful condition here being "which application is currently in focus?" But I can see a use case for other conditions, like time of day and so on.

Dbusmenuproxy may be useful here to invoke appmenu-items from fly-pie, or even have fly pie draw the menu while hiding it within the application.

## The Alternatives

The are no GUI alternatives.

**Comment by developer91234** [comment]
Yeah, I guess a the fly pie interface is not a good fit for a full menubar replacement. Picking out specific actions from the menubar and placing them into the fly pie menu could still be an invaluable feature however.

For a full menubar replacement, one could have popup menubar widget with a search box at the top.

```
-------------
| [search]  |
| ----------- |
| [File]      |
| [Edit]      |
| [Help]     |
-------------
```

ofc this is outside the scope of your existing UI model *but* it would be very nice thing nonetheless. It would liberate the global menu idea from the Apple UI model and turn it into just another popup/popup-menu.

**Comment by developer91234** [comment]
Fildem isn't a popup menu, it's a global menu bar. Global menu isn't a good fit for Linux desktop IMO.

> Yeah, that's definitely not in the scope of Fly-Pie

It would be within the scope of "popup menu", just not "marking popup menu." So the question is whether you want to include *other types of menus* - like vertical context menus - under the scope of your project. I think it's an idea worth considering because other types of menus can be superior to marking menus for certain tasks. For example, with context menus, you could open a vertical clipboard history menu at the cursor position.

**Comment by Schneegans** [comment]
Rescheduled as Fly-Pie 12 will be a bug-fix-only release.

**Comment by Schneegans** [comment]
Rescheduled to Fly-Pie 14, as Fly-Pie 13 will be released soon because it includes an important bug fix.

**Comment by Schneegans** [comment]
Rescheduled again as Fly-Pie 14 will focus on GNOME 42 support...

**Comment by luka-n** [comment]
I feel like like this could be a real killer feature, I certainly would love to see it

**Comment by Schneegans** [comment]
I am currently investigating ways to create a standalone (not GNOME-only) version of Fly-Pie. I have some ideas in mind which could improve the user experience. Context-aware menus will definitely be a core feature of this new version.

**Comment by blipk** [comment]
Hi @Schneegans would that work on Wayland as well or X11 only?

I'd be interested in adding a simple version of this feature request that simply opens a different menu depending on the currently active window.

I have some experience with working with windows workspaces on my extension https://github.com/blipk/Customised-Workspaces

It'd be great if you could point me to where might be the best place in your code to hook into the keyboard shortcuts and menu configuration, and any style/contribution guidelines.

I propose adding an `application` config item which points to either an xdg application or a window wmclass, and any menus that have the same keyboard shortcut would be preferred by the currently focused window application/wmclass

If you're interested, let me know and I will look into creating a PR.

**Comment by blipk** [comment]
Actually it looks like the simplest solution was to use this other extension and some DBus calls: https://github.com/hseliger/window-calls-extended

And then bind a gnome global keyboard shortcut to a shell script with the following:
```Shell
FOCUSED_WMCLASS=$(gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/WindowsExt --method org.gnome.Shell.Extensions.WindowsExt.FocusClass)
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/shell/extensions/flypie --method org.gnome.Shell.Extensions.flypie.ShowMenu "${FOCUSED_WMCLASS//[,()']/""}"
```

I just then have to name my menus in flypie after the the applications main window WMCLASS, and now I get a different menu for each application with a single keyboard shortcut.

**Comment by Schneegans** [comment]
@blipk This is a pretty clever use-case of Fly-Pie's DBus interface!! And it's actually pretty easy to set up. Would you still be interested in looking into the code or is this solution sufficient for now? Implementing this into Fly-Pie will be waaay more complicated, I guess :laughing:

**Comment by blipk** [comment]
Hey @Schneegans thanks, I'd probably just stick with the script for now as it's working well, I'm looking forward to using this with my wacom tablet when that arrives.

It shouldn't be too hard to implement, most of the calls to find the focused window are easy enough, but I'm not familiar with your code so would take me a bit of time to fit it in with your config/setup.

I'm more interested in the version you're working on that's not gnome-dependant.

**Comment by Schneegans** [comment]
@blipk I published some [news regarding the platform-agnostic pie menu](https://ko-fi.com/post/Introducing-Ken-Do-L3L7L0FQ2)! At the end of the post, I wrote down some ways how you could contribute to the project. I would be more than happy if you would follow the progress and support the development along the way :smile:

**Comment by Schneegans** [comment]
I will not add this feature to Fly-Pie as I am currently focusing on the successor project [Kando](https://github.com/kando-menu/kando). Application-dependent menus will become a core part of Kando!
