### ISSUE TITLE
Fly-Pie Settings Can't Be Displayed

### ISSUE THREAD

**Issue by Vinnyboiler** [Schneegans/Fly-Pie#158]
## Describe the Bug
The settings are showing a error and refusing to display:

> Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

>Stack trace:
  @/home/vinny/.local/share/gnome-shell/extensions/flypie@schneegans.github.com/src/prefs/ExampleMenu.js:11:19
  @/home/vinny/.local/share/gnome-shell/extensions/flypie@schneegans.github.com/src/prefs/TutorialPage.js:20:23
  @/home/vinny/.local/share/gnome-shell/extensions/flypie@schneegans.github.com/src/prefs/PreferencesDialog.js:19:28
  @/home/vinny/.local/share/gnome-shell/extensions/flypie@schneegans.github.com/prefs.js:13:27
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  

Steps to reproduce the behaviour:
1. Go to Gnome Extensions
2. Click On the settings gear
3. See error

You may also check the output of GNOME Shell for any error messages related to Fly-Pie.
This can be done with the following terminal command:

journalctl -f -o cat | grep -E 'flypie|'

> Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 20).
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4a00042
Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 20).
Window manager warning: last_focus_time (7627230) is greater than comparison timestamp (7627229).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: last_user_time (7627230) is greater than comparison timestamp (7627229).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: 0x4a00042 appears to be one of the offending windows with a timestamp of 7627230.  Working around...
Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 20).
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4a00042
Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 20).
Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 20).
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4a00042
Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 20).

## Expected Behaviour
The settings to load

## System
 - Linux distribution - Pop!_OS 21.04 x86_64 
 - Fly-Pie version - Fly-Pie 8
 - GNOME Shell version: bash 5.1.4 (I apologise I'm new to Linux and not sure if that's correct0

**Comment by Schneegans** [comment]
I just released Fly-Pie 9 which includes this as a fix as it seems to affect multiple users.
