### ISSUE TITLE
Add German translation - What to translate?

### ISSUE THREAD

**Issue by daPhipz** [Schneegans/Fly-Pie#16]
Heyho!
This looks very cool! :+1:
I would like to contribute a German translation, but I have absolutely no idea where to find the Strings that need translating.
Could someone maybe point in the right direction?

**Comment by Schneegans** [comment]
Thank you! Fly-Pie is not yet translatable. Once localization support is implemented, I will come back to you! I will leave this issue open till then.

**Comment by daPhipz** [comment]
OK cool :+1: 
Is there anything else a not-very-Programmer-y person can do to help you out?

**Comment by Schneegans** [comment]
I have an idea: If you want to, you could create some awesome theme presets!

**Comment by Schneegans** [comment]
I added now the possibility to translate Fly-Pie in `develop`. However, as German is my mother tongue as well, I already translated it on the way. It would be great, if you could check the translation for any spelling errors! Also, feel free to suggest better translations, some of the terms sound quite weird in German :wink: 
Thank you!

**Comment by daPhipz** [comment]
Aw bummer...
I also speak French, so maybe I can provide a translation there. Although I do understand it quite well, my translations might still be shit. Quality control is definitely necessary!
