### ISSUE TITLE
when I move something to stash, a "random" menu disappears

### ISSUE THREAD

**Issue by TavoAdr** [Schneegans/Fly-Pie#162]
## Describe the Bug
when I move something to stash, a "random" menu disappears

1. Go to 'Menu Editor'
2. Drag something to 'stash'

## Expected Behavior
 A "random" menu disappears

## System
 - Pop! os 21.04
 - Fly-Pie 9
 - GNOME Shell 3.38

**Comment by Schneegans** [comment]
Thanks for the report! This seems to be a GTK3-only issue. I think I fixed it with the latest commits to the `develop` branch. You can [clone the latest version from git](https://github.com/Schneegans/Fly-Pie/blob/develop/docs/installation.md#c-cloning-the-latest-version-with-git) and see if it works now!
