### ISSUE TITLE
Cannot delete items from the menu builder

### ISSUE THREAD

**Issue by yashimoto** [Schneegans/Fly-Pie#17]
## Describe the Bug
I cannot delete any menu item.

1. Go to Fly Pie settings in GNOME Tweaks
2. Click on Menu Editor
3. Select item to delete
4. Click "Ok" button in confirmation dialogue

## Expected Behavior
I expected the menu item to be deleted.
I expected the cancel button to close the dialog. 

## System
 - Linux distribution [Pop!_OS 20.04 LTS]
 - Fly-Pie version [Installed from GNOME Extensions on Sep 4 2020]
 - Gnome Shell version: [3.36.3]

![ErrorScreenShot](https://user-images.githubusercontent.com/4257695/92312664-21072900-efc3-11ea-921e-b3623895005e.png)

**Comment by Schneegans** [comment]
Thank you for the report! I do not really understand what happens on your side. What happens when you click on the OK or the Cancel button? Does the dialog close? Or are the buttons un-clickable?

**Comment by yashimoto** [comment]
Hi Simon,

The dialogues buttons are clickable, however, the don't trigger any action
(the menu item is not deleted, nor can the dialogue box be closed)
Here's a little video of the bug.

Thanks for your efforts, I think FlyPie is supercool :)

Best
Yash

**Comment by Schneegans** [comment]
I just pushed something to the `develop` branch which could fix the issue. Could please try to remove Fly-Pie and install the latest version from `git`? Here's a guide: https://github.com/Schneegans/Fly-Pie#cloning-the-latest-version-with-git

I can also provide a step-by-step guide if you are not used to the command line!

Thank you for testing this!

**Comment by yashimoto** [comment]
Thanks Simon.

It worked :)

Best
Yash
