### ISSUE TITLE
ClipboardManager: owner is null

### ISSUE THREAD

**Issue by Leleat** [Schneegans/Fly-Pie#170]
## Describe the Bug

I don't know, if there are any functional problems. I've only noticed these errors in the logs.

**Steps to reproduce the behavior:**

1. Open the 'Characters' app (also works with Firefox and probably any app I guess)
2. Copy a character
3. Close the app
4. Error(?):

```
JS ERROR: TypeError: owner is null
ClipboardManager/this._clipboardConnection<@/home/timmy/.local/share/gnome-shell/extensions/flypie@schneegans.github.com/src/extension/ClipboardManager.js:118:17
```

## Expected Behavior
\-

## System
 - OS: Fedora 35
 - Fly-Pie version: current Super-RMB branch
 - GNOME Shell version: 41.1

**Comment by Schneegans** [comment]
Thanks for the report! Somehow I didn't notice that the `owner` in this method can get `null` :smiley:
