### ISSUE TITLE
Global scaling should not scale the font

### ISSUE THREAD

**Issue by 1player** [Schneegans/Fly-Pie#171]
## Describe the Bug

Global scaling scales the font as well, so to keep the centre label legible, one needs to halve the size otherwise it's too large. In my case scaling is used because I'm running on a 4K screen at 200% scaling, and by default Fly-Pie is too tiny to be useful.

## Steps to reproduce
1. Set a decent, legible font size (say 11)
2. Double the global scaling setting
3. Labels are rendered at an effective size of 22, I have to change the font size to 5.5 for it to be rendered at size 11

## Expected Behavior

Global scaling not to affect rendered text, which exactly like GNOME scaling works.

## System
 - Fedora 35
 - Fly-Pie 11
 - GNOME 41 on Wayland

**Comment by Schneegans** [comment]
Thanks for the suggestion! I see your point. However, I am not sure whether this behavior would be more intuitive.

An alternative would be to incorporate the current display scale automatically. If display scaling is set to 200%, Fly-Pie could draw itself automatically with a scaling factor of 200% (while not affecting the font size).

I guess that this would be an even better solution. What do you think?

**Comment by 1player** [comment]
That certainly would be better. The global desktop scaling should affect all apps. A 4k screen at 200% global scaling should have all of its apps render as if they were on a 1920x1080 screen. As it stands, without global scaling, the default Fly-Pie look is half of what it should be.

**Comment by Schneegans** [comment]
I'll look into it. The main problem will be setups where you have multiple monitors with mixed scalings. Fly-Pie caches a lot of icon graphics and in such a case it would need all icons at different resolutions... maybe I have to invalidate the cache whenever a menu is opened on another monitor...

**Comment by Schneegans** [comment]
Rescheduled as Fly-Pie 12 will be a bug-fix-only release.

**Comment by Schneegans** [comment]
Rescheduled to Fly-Pie 14, as Fly-Pie 13 will be released soon because it includes an important bug fix.

**Comment by Schneegans** [comment]
This was much more involved than I anticipated :smile: Fractional scaling works completely different on Wayland and X11...

However, I hope that it works now. Fly-Pie should now properly react to the configured display scaling (no need to fiddle around with the global scaling!). If you want to, you can checkout the `main` branch (there's a [guide](https://github.com/Schneegans/Fly-Pie/blob/main/docs/installation.md#c-cloning-the-latest-version-with-git) available) and test if it works for you.
