### ISSUE TITLE
Overlapping settings in Advanced Settings

### ISSUE THREAD

**Issue by humanplayer2** [Schneegans/Fly-Pie#175]
## The Bug
Under Settings > Advanced Settings, the two top settings a rendered on top of each other. See attached screenshot.

![Screenshot from 2021-12-03 23-25-43](https://user-images.githubusercontent.com/220154/144681454-aa597627-fc1b-47fe-88a3-7e1873339877.png)

1. Go to Settings > Advanced Settings
2. See error

## Expected Behavior
That the settings are not rendered on top of each other :)

## System
_Please complete the following information:_
 - Linux distribution: Pop!_OS 21.04
 - Fly-Pie version: 11
 - GNOME Shell version: 3.38

**Comment by Schneegans** [comment]
Thanks for the report! Things like this happen, if you try to support GTK3 and GTK4 at the same time... I'll release a new version of Fly-Pie rather soonishly, as there seem to be some bugs which need to be fixed.
