### ISSUE TITLE
Super-RMB: Overview will be opened, if you activate a menu item with LMB while holding Super

### ISSUE THREAD

**Issue by Leleat** [Schneegans/Fly-Pie#176]
## Describe the Bug

If you activate a pie menu with `Super`+`RMB` but use `LMB` to activate an item while holding `Super`, the overview will be opened after letting go of `Super`.

1. Open a pie menu with `Super`+`RMB`
2. Hold `Super`
3. Activate a menu item with `LMB`
4. Let go of `Super`

=> Overview will open.

## Expected Behavior
Overview shouldn't open.

## System
 - Fedora 35
 - Fly-Pie version: 11 (EGO)
 - GNOME Shell version: 41.1

**Comment by Schneegans** [comment]
Thanks for the report! I pushed a fix which should ensure that the menu does not close until <kbd>Super</kbd> is released. If you want to, you can test it in `develop`. I will publish a bug-fix release quite soon!

**Comment by Leleat** [comment]
> Thanks for the report! I pushed a fix which should finally ensure that the menu does not close until Super is released. If you want to, you can test it in develop. I will publish a bug-fix release quite soon!

Thanks, I'll give it a shot.
