### ISSUE TITLE
Launching an app may not center the correct window

### ISSUE THREAD

**Issue by Leleat** [Schneegans/Fly-Pie#183]
## Describe the Bug

If you launch an app, Fly-Pie will center the next opened window at the pointer position. This doesn't work for apps, which take long to load (for example GIMP, Steam, etc.). It's possible to hit the 2s 'listening' timeout or the user may open a different app while the other app, which was launched with Fly Pie, is loading.

Another problem are loading screens ;although these are even more of an edge case. Some apps seem to  trigger the openNextWindowAtPointer code with their loading screens (for example Steam and Discord). Not sure, if there is a good way to workaround it. Only thing I could think of is to check wether the window allows resize _and_ move operations (Discord's loading screen is moveable for some reason...).

**(Not sure, if this is a bug or wether you just wanted to keep it simple and not bother with all kinds of edge cases...)** 

## Expected Behavior
The window of the app from the pie menu should be centered.

## System
 - Linux distribution: Fedora 35
 - Fly-Pie version: 12 (EGO)
 - GNOME Shell version: 41.1

**Comment by Schneegans** [comment]
Yeah, I think there's no way this could work 100% of the time. Increasing the 2s is not a good solution as it will also increase the likelihood that the users opens something else in the meantime. And I think there's no way to get multiple-windows applications to work (in some cases, such as old-school GIMP which always opened several windows, you don't even want them to be positioned at the pointer).

Alas, we _could_ try to get the process IDs belonging to the windows, compare them, check for multiple windows owned by the same process etc... But as you said, this would make the code much more complicated.

Another counter argument is, that if an application takes so long, you will most likely have done something else and moved your pointer in the meantime. Then opening the window at the position where you activated the item, will not be very helpful for reducing mouse travel.

Problematic are apps which take approximately two seconds. They will be opened at the pointer half of the time, which will be very confusing. But also here, I see no obvious way to fix this.

**Comment by Schneegans** [comment]
I'll mark this as "wontfix", but if anybody has a good idea, we can reopen this!

**Comment by Leleat** [comment]
> Increasing the 2s is not a good solution as it will also increase the likelihood that the users opens something else in the meantime.

> Another counter argument is, that if an application takes so long, you will most likely have done something else and moved your pointer in the meantime. Then opening the window at the position where you activated the item, will not be very helpful for reducing mouse travel.

My initial idea was to increase the timer, check for the created-windows' app and compare it to the app from the pie menu. Then grab the pointer pos just before you move the window.

> And I think there's no way to get multiple-windows applications to work (in some cases, such as old-school GIMP which always opened several windows, you don't even want them to be positioned at the pointer).

That would be indeed very problematic and I didn't think about that 😅...

**Comment by Schneegans** [comment]
>  check for the created-windows' app and compare it to the app from the pie menu

This will be hard. For the apps which are directly launched from Fly-Pie it could work (but even this is difficult, if the user just gave an executable name, I am not sure if I can map this to a window). However, for apps which are indirectly launched (Like with the "Open URI", "Open File", "Recent Files", "Bookmarks", or "Devices") it will be harder. How do I know whether an URL opened a new tab or a new window? Same with the file manager, e-mail client, image viewer...
