### ISSUE TITLE
Can't start tutorial because settings menu is longer than the screen.

### ISSUE THREAD

**Issue by Abhinav1217** [Schneegans/Fly-Pie#187]
## Describe the Bug
I opened the settings panel for the fly-pie from extensions app. It opens with size beyond my screen. I tried reducing the size of the app but it doesn't shrink a lot. I even tried to move it on my external monitor which is larger but still I can only manage to see up until the first paragraph of the menu. There should be a scrollbar to access such long page similar to other gnome apps. 

![Screenshot from 2021-12-16 09-13-40](https://user-images.githubusercontent.com/740584/146304829-888740ed-877f-49a6-b37b-6512f5c5de68.png)
![Screenshot from 2021-12-16 09-11-43](https://user-images.githubusercontent.com/740584/146304836-1b050a61-7167-49ad-8572-5d479dc90ae5.png)

**Logs**
```
abhinav@abhinav-sol ~ $ journalctl -f -o cat | grep -E 'flypie|'
[session uid=1000 pid=1600] Successfully activated service 'org.freedesktop.Tracker3.Miner.Extract'
Started Tracker metadata extractor.
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
tracker-extract-3.service: Succeeded.
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed

^C
```

## Expected Behavior
Settings app should open at the size of screen allowing me to click the button below and continue with tutorial. There should be a scrollbar on the app.

## **System Information :** 
Solus OS
Lenovo Y50 Laptop with 15 inch screen 16:9 (1920x1080)
Fly-pie installed from EOG.
```
abhinav@abhinav-sol ~ $ uname -a
Linux abhinav-sol 5.14.21-210.current #1 SMP PREEMPT Sun Dec 5 21:23:09 UTC 2021 x86_64 GNU/Linux
abhinav@abhinav-sol ~ $ gnome-shell --version
GNOME Shell 41.1
```

**Comment by Schneegans** [comment]
That looks weird :)

Is this the standard Adwaita theme? If not, you could try switching the GTK theme and test if this changes something. It could also help if you provide screenshots of the other pages of the preferences dialog ("Settings", "Menu Editor", and "Achievements"). One of those should contain widgets which are unnaturally large causing the entire dialog to stretch vertically...

**Comment by Abhinav1217** [comment]
> Is this the standard Adwaita theme? If not, you could try switching the GTK theme and test if this changes something.

Tried after disabling the user theme extension altogether. Still same issue. 

> if you provide screenshots of the other pages of the preferences dialog ("Settings", "Menu Editor", and "Achievements"). One of those should contain widgets which are unnaturally large causing the entire dialog to stretch vertically...

If you zoom into the gome-shell overview screenshot, you can see the button I am supposed to click is way at the bottom. There is also another paragraph which is not visible. All other pages on preferences dialog are same size based on what I can deduce from overview screen. 

Only other extension that I have with long preference page is arc-menu. It has scrollbars so it can be resized vertically. On Fly-pie, I can resize horizontally but not vertically. As You can see on the screenshot, Scrollbar is visible in other extension settings when I scroll or put my mouse on top of it. 
![Screenshot from 2021-12-16 21-42-04](https://user-images.githubusercontent.com/740584/146407948-27683a7f-32cb-4949-81f6-3602bcc5b9a4.png)

**Comment by Schneegans** [comment]
It's not a problem of missing scrollbars. The settings dialog shouldn't be that long. It usually looks like this:

![Screenshot from 2021-12-16 19-45-55](https://user-images.githubusercontent.com/829942/146430428-05d95032-4b4d-4a8d-a543-5e5a429b449f.png)

> Tried after disabling the user theme extension altogether. 

I was talking about your GTK Theme, not the Shell theme. Which GTK theme are you using?

Again, could you please try to make screenshots of the "Settings", "Menu Editor", and "Achievements" pages? (ideally from the overview as you did before). Something must be messed up on either of these other pages.

**Comment by Abhinav1217** [comment]
I usually use a community maintained [arc gtk 4 theme ](https://github.com/jnsh/arc-theme). My installation was updated about 3 months ago. 

But for the purpose of reporting this bug, I switched to default adwaita theme, to make sure this was not an issue on my end. 

Here are the following screenshot ( I used alt+print function in gnome which takes screenshot of active window )


![achievements](https://user-images.githubusercontent.com/740584/146516606-d43f9a54-1cd3-4c92-b0cc-3dcdc32faca8.png)
![menu_editor](https://user-images.githubusercontent.com/740584/146516610-21c7cf3b-c788-49d5-a3b4-d7f33834ea51.png)
![settings](https://user-images.githubusercontent.com/740584/146516611-d7a5c616-1f7d-481a-a505-0856bdc10c18.png)
![Screenshot from 2021-12-17 14-04-45](https://user-images.githubusercontent.com/740584/146516613-f3176b9e-28a4-4900-82f9-8601dc26e256.png)
![Tutorial ](https://user-images.githubusercontent.com/740584/146516617-c3fa4693-9c4d-4c37-bb62-32ccbff42cca.png)

**Comment by Schneegans** [comment]
Thank you! I am still thinking that it could be a theming issue. It's weird that your original screenshots look like Adwaita even if you're using Arc. GTK4 support for Arc [has only landed recently](https://github.com/jnsh/arc-theme/issues/61) so I suspect that your version of the theme does not support GTK4 yet.

Have you logged out after switching to the default Adwaita theme? Things like widget spacing are sometimes not updated properly when switching GTK themes and require a log-out / log-in cycle.

**Comment by Abhinav1217** [comment]
To clearify. Original screenshot is Adwaita. Before submiting issue, I switched theme to adwaita to make sure this issue is not happening because of something at my end.

**Comment by Schneegans** [comment]
I just downloaded Solus OS and run it in a VM. It uses the Materia GTK theme as default theme and everything looks good.
![Screenshot from 2021-12-17 21-52-42](https://user-images.githubusercontent.com/829942/146606686-d74ed708-4fc2-42bc-8752-d7dfd601c038.png)

To be honest, I am not sure how to proceed here.
There are also some weird spaces in the text in your screenshots. Here's a crop of one of your screenshots (note the random spaces between the letters):

![image](https://user-images.githubusercontent.com/829942/146606853-75d6236f-f4bb-4e98-9a12-42da720095cf.png)

Especially on the achievements page the vertical spacing looks totally random. It's not evenly stretched, some items take much more vertical space than others.

**Comment by Abhinav1217** [comment]
I have increased font size and change default fonts using tweak tools for better visibility. Could that cause this in any way?

If I create a new user on my system, it should have all the GTK defaults without any tweaking. Let me report back after trying that out.

**Comment by Abhinav1217** [comment]
This is something new, Does this help?

```
$ journalctl -f -o cat | grep -E 'flypie|'
Unable to fetch the list of available renderers: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.intel.dleyna-renderer was not provided by any .service files
value "nan" of type 'gfloat' is invalid or out of range for property 'translation-y' of type 'gfloat'
value "nan" of type 'gfloat' is invalid or out of range for property 'translation-y' of type 'gfloat'
value "nan" of type 'gfloat' is invalid or out of range for property 'translation-y' of type 'gfloat'
```

I don't see spacing issue in the test user which has gtk defaults, so maybe the spacing was caused by my increasing font-size from 9 to 12 or by replacing default fonts with my preferred one. But out of bounds size is still issue.
![Screenshot from 2021-12-20 12-54-52](https://user-images.githubusercontent.com/740584/146736676-222ad624-010c-4043-bcc1-aeca2672eb6e.png)

**Comment by Schneegans** [comment]
If that log message comes from Fly-Pie, it may be a hint... However, this log may contain messages from any application on your system. To be sure that it comes from Fly-Pie, could you please do these steps:
1. Open a terminal and run the command ` journalctl -f -o cat | grep -E 'flypie|'`. Keep the terminal open and watch the output during the next step.
2. Open the preferences of Fly-Pie.
3. Watch the output in the terminal. There should be a line containing `Activating service name='org.gnome.Shell.Extensions' requested by ':xxxxx' (uid=1000 pid=xxxxx comm="gnome-extensions prefs flypie@schneegans.github.co" label="unconfined")`
4. Copy whatever was logged after this line until the preferences dialog was fully shown and paste it here.

**Comment by Abhinav1217** [comment]
I have been using the command you mentioned above from the start, it was mentioned in your github issue template when I opened this issue.   

I found on stackoverflow on how to clear journalctl logs, and used `sudo journalctl --rotate --vaccume-time=1s --vaccume-size=1m` to clear old logs from journalctl.  

```
$ journalctl -f -o cat | grep -E 'flypie|'
[session uid=1002 pid=1523] Successfully activated service 'org.gnome.Extensions'
[session uid=1002 pid=1523] Activating service name='org.gnome.Shell.Extensions' requested by ':1.120' (uid=1002 pid=3109 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Exte" label="unconfined")
[session uid=1002 pid=1523] Successfully activated service 'org.gnome.Shell.Extensions'
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a00004
g_task_return_error: assertion '!task->ever_returned' failed
Some code accessed the property 'MessageTray' on the module 'main'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x2a76340] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x432ef10] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x4330dd0] is on because it needs an allocation.
(EE) event7  - SynPS/2 Synaptics TouchPad: libinput bug: invalid gesture event GESTURE_EVENT_PINCH in state GESTURE_STATE_NONE
loading user theme: /usr/share/themes/Materia-dark/gnome-shell/gnome-shell.css

```

After this point when I closed the preferances This was logged
```
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400004
[impatience] enabled
[impatience] setting new speed: 0.5
```

Then I reopened the preferance dialog

```
Unable to fetch the list of available renderers: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.intel.dleyna-renderer was not provided by any .service files
JS LOG: Ignored exception from dbus method: Gio.IOErrorEnum: GDBus.Error:org.gnome.gjs.JSError.Error: Already showing a prefs dialog
```


PS: If you need, I don't mind giving you remote desktop controls to you if it helps speedup your process. I have no knowledge of how extensions works internally and how to use looking glass or how to debug this.

**Comment by Schneegans** [comment]
Hi there! Is this still an issue on your end?

**Comment by Abhinav1217** [comment]
Yes, But I think it is issue with Gnome42, OpenWeather extension also started showing similar issue where the buttons just went beyond screen with no way to reduce the window size, and scrollbar is missing.
