### ISSUE TITLE
Toplevel pie not drawn properly

### ISSUE THREAD

**Issue by TomSteu** [Schneegans/Fly-Pie#19]
System: Fedora Workstation 32, Wayland, Gnome Shell 3.36.5

Hi Simon,

I encountered a weird bug on my system, where the toplevel pie is not drawn as intended:

- whenever a toplevel pie is launched, the background is darkened, the wedges are drawn properly, but no pie appears
- moving around the pointer reveals that the pie center will only be drawn as long as it is not hovered over, and disappears whenever the pointer is on it
- its children will only be drawn as long as they are hovered, and disappear again when they are not 
- all lower level elements seem to be drawn properly
- this behaviour is persistent with all theme choices, including the light and dark presets
- also, the behaviour is there no matter how the pies are opened
- this happens to the preview pie and the tutorial as well
- in the live preview, after switching the hemisphere once, the toplevel pies are drawn correctly
- the weirdest part: I tried to record the behaviour with the screen capture instead of writing this monsterous text block, but there it appears correctly! 

Let me know if you need more information.

**Comment by Schneegans** [comment]
This sounds like it's going to be hard to debug... :smiley: 

Your description makes me remember a problem I struggled a lot with during the development. It seems, that the scene graph of Fly-Pie is so complex that Clutter sometimes loses track of which parts of the screen need to be repainted. See the comment for this line: https://github.com/Schneegans/Fly-Pie/blob/develop/daemon/Menu.js#L127.

It would be great if you could uninstall Fly-Pie (if installed from extensions.gnome.org) and install the latest version from `git`. Here's a guide: https://github.com/Schneegans/Fly-Pie#cloning-the-latest-version-with-git. Then you could try moving the line of code I linked by two lines (to line 129, right above the `return` statement). This way, it will be called whenever you move your mouse and not only when dragging items. Then restart Gnome Shell with <kbd>Alt</kbd> + <kbd>F2</kbd>, <kbd>r</kbd> + <kbd>Enter</kbd> (no, you're on Wayland - you need to logout and login again). Let's see if this makes any difference.

**Comment by Schneegans** [comment]
By coincidence, I just realized that if you disable "Animations" in the gnome-tweak-tool, Fly-Pie starts to behave like you explained. Can you check whether this is unchecked on your side?

**Comment by TomSteu** [comment]
Yes, I indeed had animations disabled! Switching them on resolves the problem. Think I will keep it on from now in order to use fly-pie. 

I'm unfortunately running some lengthly simulation atm and can't restart the gnome-shell to try your other suggestion -- but queuing redraws on any mouse move sounds like it is going to clog up the event loop.

No idea what mutter is doing instead when animations are disabled. However, using the fly-pie how it is intended while not allowing for animations is probably nonsensical in itself. It would be ok with me if you want to write a note of this into the README or so and close the issue.

**Comment by Schneegans** [comment]
I will check whether there's a workaround. If not, I will add a note to the README.
