### ISSUE TITLE
Cannot open hidden files (dotfiles) 

### ISSUE THREAD

**Issue by rdgh8** [Schneegans/Fly-Pie#197]
## Describe the Bug

There does not seem to be a way to open hidden files with this extension. Selecting with the inbuilt file selector does not work. Pasting a file path to a hidden file also does not seem to work. 

Attempt in any way to have flypie open a hidden file. 

You may also check the output of GNOME Shell for any error messages related to Fly-Pie.
This can be done with the following terminal command:

After pasting ~/.bashrc into the file path and attempting to open the file using flypie:
journalctl -f -o cat | grep -E 'flypie|'
```
[27101:27101:0100/000000.360142:ERROR:vulkan_device_queue.cc(222)] Vulkan: NVIDIA GeForce GTX 1060
Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 20).
Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 20).
[flypie@schneegans.github.com/src/common/actions/File.js:94:17] Failed to open file: Gio.IOErrorEnum: Operation not supported
Started Application launched by gsd-media-keys.
Could not create transient scope for PID 27268: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 27268 does not exist.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x380000b
Can't update stage views actor MetaWindowGroup is on because it needs an allocation.
Can't update stage views actor MetaWindowActorX11 is on because it needs an allocation.
Can't update stage views actor MetaSurfaceActorX11 is on because it needs an allocation.
[flypie@schneegans.github.com/src/common/actions/File.js:94:17] Failed to open file: Gio.IOErrorEnum: Operation not supported
```

## Expected Behavior

Some way to select hidden files with the file selector, and for the file to open. 

## System
_Please complete the following information:_
 - Linux distribution [e.g. Ubuntu 20.04]
 Pop!_OS 21.10
 - Fly-Pie version [e.g. Fly-Pie 3, or commit SHA]
 12
 - GNOME Shell version: [e.g. 3.36.2]
 40.5

**Comment by Schneegans** [comment]
I just tested it on Ubuntu 21.10 and it works as expected.

>  Selecting with the inbuilt file selector does not work.

What exactly did not work? Are the hidden files invisible? They should be shown with <kbd>Ctrl</kbd>+<kbd>H</kbd>. Alternatively, you can drag and drop the file from your file manager to the menu editor of Fly-Pie.

https://user-images.githubusercontent.com/829942/147821523-cdbe7d0b-1340-4018-9bd1-e99435dd4847.mp4

**Comment by rdgh8** [comment]
Did not know that, thank you!
