### ISSUE TITLE
Ability to activate some sort of notification status, or parts of the appearance on a currently active touch button

### ISSUE THREAD

**Issue by MostHated** [Schneegans/Fly-Pie#203]
## The Motivation
I have a few touch buttons I keep out of the way which call scripts that do different things, such as turn on lights by making HTTP requests to my home automation system, etc. I find touch buttons are great for that. What would make them over-the-top great is if they could receive data and use it to subtly, or not so subtly, change their appearance. 

## The Solution
Similar to the current d-bus data ingest in which a menu can be dynamically created and opened, additional actions could be available to currently active touch buttons. One could be to breathe the opacity value of a thin colored ring/border highlight around the button to indicate that it has received some sort of information. Upon clicking on the button, the center ring could display a message payload relevant to the options available to the button, allowing me to then select the appropriate button to press based on the information I have just received. 

In addition to colored border, perhaps configurable icons could display/flash occasionally where the button itself stays in a dim/faded state, but the icons become opaque and prominent every few seconds/minutes until acknowledged. 

## The Alternatives
Since I just thought of this, I have not really thought of alternatives when it comes to this particular application. The only real alternative I have at this point is finding another dedicated application to have persistent on-screen notifications, and up to this point, aside from Conky, which really isn't ideal for this. It took much longer than I would like to admit for just the simple setup that I currently have.

This is just a touch button and overlaying it on top of one of my Conky panels that displays Ok/Not Ok status of various services I have running on different systems, then I can start diagnostic scripts, or issue service restarts, etc:

![](https://i.imgur.com/E8DxkdW.png)

It would be great to send notifications directly to a button since it is actionable, and much more easily customizable. Honestly, if this could have fixed placement Rect panels as well as circular buttons that could receive and display data, it could possibly even replace my Conky setup, but that is me just getting off track at this point.

I appreciate your time and consideration
Thanks,
-MH

**Comment by MostHated** [comment]
I can definitely understand that some of that would be out of scope. I do appreciate the recommendations, though. I will be sure to give them a try in the next day or two. :+1:

**Comment by Schneegans** [comment]
I guess that I can close this issue. If there's anything, feel free to comment!
