### ISSUE TITLE
Dragging Not working Under Wayland Properly

### ISSUE THREAD

**Issue by THEBATEZIOPARKER** [Schneegans/Fly-Pie#211]
Dragging/Arranging In settings Not working Under Wayland Properly.

In X11 it is working properly :-
https://user-images.githubusercontent.com/87817029/157382166-67018f89-a37e-4860-ab7c-eeb0931e8620.mp4

But in Wayland it is working like this:-
https://user-images.githubusercontent.com/87817029/157382264-dcfe1a99-86e1-498f-95d6-c76fa0d4ad04.mp4

**Comment by Schneegans** [comment]
Hi there, thanks for the report!

However, I can not reproduce this on my end. Could you please provide some additional information, such as:
* Which distro are you using? 
* Which GNOME version are you on (`gnome-shell --version`)
* Which version of Fly-Pie are you using (this is shown when you click on the light-bulb icon in the titlebar)
* The output of `journalctl -f -o cat` while you reproduce the issue on Wayland

**Comment by THEBATEZIOPARKER** [comment]
I am Using Fedora 35, Gnome-41.3
Fly-Pie Version 14

The output On Wayland Shows This :-

`Started Application launched by gnome-shell.
Starting GNOME Terminal Server...
Starting dnf makecache...
Started GNOME Terminal Server.
Started VTE child process 98998 launched by gnome-terminal-server process 98979.
Metadata cache refreshed recently.
SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dnf-makecache comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dnf-makecache comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
dnf-makecache.service: Deactivated successfully.
Finished dnf makecache.
Started dbus-:1.2-org.gnome.Extensions@0.service.
(../clutter/clutter/clutter-actor.c:12417):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)
(../clutter/clutter/clutter-actor.c:12417):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)
Started dbus-:1.2-org.gnome.Shell.Extensions@0.service.
Can't update stage views actor <dashtodockContainer>[<Gjs_dash-to-dock_micxgx_gmail_com_docking_DashToDock>:0x560cd873d3c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_dash-to-dock_micxgx_gmail_com_docking_DashSlideContainer>:0x560cd79e1230] is on because it needs an allocation.
Can't update stage views actor <dashtodockBox>[<StBoxLayout>:0x560cd52060b0] is on because it needs an allocation.
Can't update stage views actor <dash>[<Gjs_dash-to-dock_micxgx_gmail_com_dash_DockDash>:0x560cd92acfd0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x560cda3e86a0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x560cd9e99f70] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashContainer>[<StBoxLayout>:0x560cd8eff5e0] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashScrollview>[<StScrollView>:0x560cd6057740] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x560cd6e444e0] is on because it needs an allocation.
Can't update stage views actor <dashtodockContainer>[<Gjs_dash-to-dock_micxgx_gmail_com_docking_DashToDock>:0x560cd873d3c0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<Gjs_dash-to-dock_micxgx_gmail_com_docking_DashSlideContainer>:0x560cd79e1230] is on because it needs an allocation.
Can't update stage views actor <dashtodockBox>[<StBoxLayout>:0x560cd52060b0] is on because it needs an allocation.
Can't update stage views actor <dash>[<Gjs_dash-to-dock_micxgx_gmail_com_dash_DockDash>:0x560cd92acfd0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StWidget>:0x560cda3e86a0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<ClutterActor>:0x560cd9e99f70] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashContainer>[<StBoxLayout>:0x560cd8eff5e0] is on because it needs an allocation.
Can't update stage views actor <dashtodockDashScrollview>[<StScrollView>:0x560cd6057740] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<StBoxLayout>:0x560cd6e444e0] is on because it needs an allocation.
BPF prog-id=383 op=LOAD
BPF prog-id=384 op=LOAD
Starting Hostname Service...
Started Hostname Service.
SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
systemd-hostnamed.service: Deactivated successfully.
SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
BPF prog-id=0 op=UNLOAD
BPF prog-id=0 op=UNLOAD
dbus-:1.2-org.gnome.Shell.Extensions@0.service: Consumed 3.980s CPU time.
`

**Comment by Schneegans** [comment]
Sorry for not getting back earlier! I totally forgot about this one. Is this still an issue with the latest version of Fly-Pie?

**Comment by THEBATEZIOPARKER** [comment]
The Issue has been fixed in the newer version
