### ISSUE TITLE
One hand mode (or one hand activation shortcut)

### ISSUE THREAD

**Issue by asteinba** [Schneegans/Fly-Pie#221]
## The Motivation
Provide a option to activate fly pie just with my mouse. Personally for me fly pie really excels when I'm in lazy mode and just use my mouse and don't have my hand on the keyboard (leaning back, drinking coffee, on phone call). Would be also very cool for people which have just one hand.

## The Solution
I have shortcuts in mind like:
- Pressing LMB+RMB at once. 
- Holding RMB and then click LMB once.
- Holding RMB and then double click LMB.
- Hold back mouse button and click LMB (my favorite but idk if you can cancel the back mouse event if the shortcut is detected).

Would be super cool if this is configurable.

**Comment by asteinba** [comment]
I'm also willing to work on this if you can give me a quick hint where the changes are needed :).

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion - this is definitely something which would be of great benefit. However, to the best of my knowledge, this is impossible for a GNOME Shell extension (at least on Wayland). But I would really like to be proven wrong here!

You would need to find a way to intercept mouse events before they are passed to the client windows. The only real solution for this would be to extend Mutter, I guess. I asked a [related question quite some time ago on discourse.gnome.org](https://discourse.gnome.org/t/how-to-bind-modifier-mousebutton-in-gjs/3743).

If you have an idea how to do this, I would be more than happy!

As a "workaround", I usually suggest these tools which allow you to open menus with your mouse in one or the other way:
* [Custom Hot Corners - Extended](https://extensions.gnome.org/extension/4167/custom-hot-corners-extended/): Open menus by moving your mouse to one corner of your screen!
* [Input Remapper](https://github.com/sezanzeb/input-remapper/): Bind menus to your additional mouse buttons!
* [xbindkeys](http://www.nongnu.org/xbindkeys/xbindkeys.html): X11-only alternative to Input Remapper.
* [Easystroke](https://github.com/thjaeger/easystroke/wiki): X11 only, use mouse gestures to open menus!

**Comment by Lenskiy** [comment]
I installed **ydotool** as described [here](https://askubuntu.com/questions/1413829/how-can-i-install-the-latest-ydotool-1-0-1-keyboard-automation-tool-working-on/1413830#1413830)  that is able to simulate keystrokes. For instance
`ydotool key 56:1 103:1 56:0 103:0`
simulate `<Alt>+<Up>`
You migh find this [link](https://discourse.nixos.org/t/anyone-got-ydotool-working-in-kde-plasma/19252) also useful.
Then I installed [xbindkeys](https://www.linuxuprising.com/2019/11/how-to-bind-mouse-buttons-to-keyboard.html) and created ~/.xbindkeysrc with the following lines
```
"ydotool key 56:1 103:1 56:0 103:0"
       b:2
```
Now, the middle mouse button (the scroll wheel button) is translated to `<Alt>+<Up>`. Setting up `<Alt>+<Up>` as a shortcut in Fly-Pie will open it when the middle mouse button is clicked.

**Comment by claudiusraphael** [comment]
> There is another, a better and easier solution. Install input-remapper and then by running` input-remapper-gtk` remap the middle mouse button to `<Alt>+<Up>` as follows ![image](https://user-images.githubusercontent.com/3796661/175000967-b826e868-8301-4712-b8ac-d73b2bdc0cab.png) Make sure to save the preset. In the case above it will be saved to mid.json. The config file `/home/$USER/.config/input-remapper/config.json` should contain a clause similar to
> 
> ```
>     "autoload": {
>         "Logitech M350": "mid"
>     },
> ```

Were you referring to [sezanzeb/input-remapper](https://github.com/sezanzeb/input-remapper)?

**Comment by Schneegans** [comment]
I'll close this issue (as it's not possible to implement from the Fly-Pie side). At the same time I'll pin it to the top of the issue list so that others may find the links to the third-party solutions more easily.
