### ISSUE TITLE
Import/Export configuration file by command line

### ISSUE THREAD

**Issue by D3vil0per** [Schneegans/Fly-Pie#225]
Hello,
I was looking for import/export customized configuration file by command line and I also read the https://github.com/Schneegans/Fly-Pie/issues/30 issue where is reported that for exporting by CLI you can use:
```
dconf read /org/gnome/shell/extensions/flypie/menu-configuration > menu.json
```
Then you can import the configuration with:
```
dconf write /org/gnome/shell/extensions/flypie/menu-configuration "`cat menu.json`"
```
but on my machine I don't see the file `/org/gnome/shell/extensions/flypie/menu-configuration` that should contain my custom configuration. I'm aware about the two buttons for import/export on the GUI but I need to automate some process and I would like to understand how I can do this import/export by command line on terminal.

My host is Arch Linux.

Thank you in advance

**Comment by Schneegans** [comment]
Hi there! Have you actually tried the commands? They can indeed be used to export / import the menu configuration (the dconf settings are not stored in files but rather in a database). If you want to export / import _all_ settings of Fly-Pie (not only the menu configuration) you can use these commands:

```bash
dconf dump /org/gnome/shell/extensions/flypie/ > fly-pie-settings.txt
```

```bash
dconf load /org/gnome/shell/extensions/flypie/ < fly-pie-settings.txt
```

**Comment by D3vil0per** [comment]
In case I would like to import / export only menu configuration (I guess also custom icons and related commands), and not all configuration, which dconf command must be executed?

**Comment by Schneegans** [comment]
You'll need the command you posted in the beginning. I do not know how to use `dconf` in a chroot environment. Maybe it would be easier to execute some kind of initial setup when the user first logs in? It seems [to be difficult](https://unix.stackexchange.com/questions/687514/how-to-change-dconf-settings-in-chrooted-mode-via-terminal) to do this while creating the ISO...
