### ISSUE TITLE
Fly-Pie fails to run when GDM gresource is changed

### ISSUE THREAD

**Issue by D3vil0per** [Schneegans/Fly-Pie#229]
## Describe the Bug
In a clean Arch Linux environment, when Fly-Pie is installed, it runs correctly. Then, when the user wants to change the Login Screen according to the official documentation of Arch Linux (https://wiki.archlinux.org/title/GDM#Login_screen_background_image), after the substition of the compiled file `gnome-shell-theme.gresource` to `/usr/share/gnome-shell/` and reboot, your new Login Screen is changed correctly but Fly-Pie (and Burn My Windows) don't start anymore despite they appear inside the `gnome-extensions list`. Even if you try to reinstall, it does not work.
Note that you can open the settings of Fly-Pie and Burn My Windows correctly by using `gnome-extensions prefs`.

Be careful: if you change the gresource by trying to restore the gresource of default, your login screen could break and cannot enter in the desktop environment, so please, test it in a clean environment. Save a backup of the default gresource file.

I also tried to restore then the original gresource, uninstalled and reinstalled Fly-Pie but not working anymore, despite result installed.

1. In a clean environment, install Fly-Pie according the official instructions in GitHub
2. Then, verify that Fly-Pie works correctly. It should work correclty.
3. By following the Arch Linux documentation (https://wiki.archlinux.org/title/GDM#Login_screen_background_image), change your Login Screen background image
4. Reboot
5. Fly-Pie should not work anymore despite it is installed.

The same issue affects also Burn My Windows extension.

## Expected Behavior
Fly-Pie working correctly when GDM Login Screen is changed according the Arch Linux documentation.

## System
 - Linux distribution: Arch Linux (latest version; kernel release: 5.18.2)
 - Fly-Pie version: 16
 - GNOME Shell version: 42.2

**Comment by Schneegans** [comment]
Thanks for the report - this sounds a bit weird. I am not sure how this could affect the extensions. Does this also affect other extensions? And have you checked the logs (e.g. `journalctl`)? Most likely some kind of error message gets printed...

**Comment by D3vil0per** [comment]
I didn't check other extensions over Fly-Pie and BMW. I tried to check on `journalctl` by the command suggested but it didn't produce any logs when I tried to execute the two extensions.

**Comment by Schneegans** [comment]
Could you please try this with other extensions? Maybe Just Perfection or Dash to Panel? If it also affects them, it's more likely to be an issue in GNOME Shell.

**Comment by D3vil0per** [comment]
> Could you please try this with other extensions? Maybe Just Perfection or Dash to Panel? If it also affects them, it's more likely to be an issue in GNOME Shell.

I tried with a new Arch Linux machine and I see that Fly-Pie, Burn My Window, Just Perfection and Dash to Panel work well. I think that my problem described above need another object to be triggered but I think the problem is not related to the extensions, also because now is only the GNOME top bar affected (it disappeared).

Sorry for this false positive. I close the issue.
