### ISSUE TITLE
RunningApps.js for hoverPeeking added minimize for windows that weren't already open

### ISSUE THREAD

**Issue by IJK9827** [Schneegans/Fly-Pie#232]
RunningApps.js for hoverPeeking added minimize for windows that weren't already open. I wrote some code for it, and it works for me. I'm new to github and stuff, so I just pasted it below lol. I hope you like it and it has no bugs. Maybe also add a toggle button for it. Also is_hidden can be different from minimized like on mac or something maybe.

          defaultData: {
                activeWorkspaceOnly: false,
                appGrouping: true,
                hoverPeeking: true,
                nameRegex: '',
                wasntAlreadyOpen: false
              },

......

          onSelect: () => {
            window.get_workspace().activate_with_focus(
                window, global.display.get_current_time_roundtrip());
          },

          // If hovered, we switch to the corresponding window if window peeking is
          // enabled.
          onHover: () => {
            if (data.hoverPeeking) {
              data.wasntAlreadyOpen = window.is_hidden();
              window.get_workspace().activate_with_focus(
                  window, global.display.get_current_time_roundtrip());
            }
          },
          onUnhover: () => {
            if (data.hoverPeeking && data.wasntAlreadyOpen) {
              window.minimize();
            }
          }

**Comment by IJK9827** [comment]
Also it would be nice (for me lol) if windows could be closed somehow from the menu without exiting the menu.
Also when there is a lot of children near back towards the center, the grandchild are underneath the center blob node thingy, so switch the render order somehow maybe. <

**Comment by Schneegans** [comment]
Hi there! Thanks for this contribution! This is indeed a good idea (and it's awesome that you tried to dig through the code and managed to understand it :smile: ). I could just copy your code - but we could also go the GitHub way with a proper merge request. This way you would learn something new and you would become an official contributor to this repository!

If you want to, I would explain the necessary steps!

**Comment by IJK9827** [comment]
Yeah. I should make a public fork, yeah? I noticed there are a lot of forks. I only have a local clone right now. I'll make a fork.

**Comment by Schneegans** [comment]
Yeah, basically this:
1. Fork the repository.
2. Clone the forked repository and create a new branch (e.g. `git checkout -b feature/minimize-peeked-windows`)
3. Implement the new feature and commit the changes to this branch. You can do multiple commits, or a single commit. I would appreciate it if the commit message followed the rules in the README, but it is not so important after all.
4. Push the commit to the forked repository.
5. Use the GitHub interface to create a pull request against the `main` branch of the original Fly-Pie repository. Make sure not to choose the `main` branch of your forked repository :wink: 

Then I'll review your changes, suggest some modifications and finally merge it!

**Comment by IJK9827** [comment]
Thank you, yay :tada:
