### ISSUE TITLE
Don't understand how to use - tutorial is broken on Pop_OS

### ISSUE THREAD

**Issue by cement-head** [Schneegans/Fly-Pie#235]
Is there some kind of YouTube tutorial?  The tutorial is broken on Pop-OS - missing GTK module.

I don't know how to invoke Fly-Pie.  Some basics would be nice, right now it's completely broken.  Can't even start it.  Documentation is atrocious.

**Comment by Schneegans** [comment]
I am not sure where to start. First: if **you want** that **I help you** understand the software which I am developing voluntarily in my spare time, I would suggest not to call it it or its documentation **atrocious**.

Second: You completely ignored the bug report template. So I have to spent my time asking you for all those things. What GNOME Shell version are you using? Wayland or X11? What Pop-OS version? What is broken? How can the issue be reproduced? Is there an error message logged? How am I supposed to help you if all I get from you is "completely broken"?

Third: If you are missing some vital information in the [first steps guide](https://github.com/Schneegans/Fly-Pie/blob/main/docs/first-steps.md), I would happily receive a pull request!

**Comment by cement-head** [comment]
Sorry - CNTRL+SPACE is all that I needed.
