### ISSUE TITLE
Some keyboard shortcuts don't show up in menu editor main area

### ISSUE THREAD

**Issue by jle64** [Schneegans/Fly-Pie#236]
## Describe the Bug

Some keyboard shortcuts don't show up in menu editor main area. This happens for example when setting "Super + <" as shortcut for a menu (see capture: while the shortcut is set (right emphasis) it does'nt show up (left emphasis)).
![missing_shortcut](https://user-images.githubusercontent.com/7120882/180582869-4ca770ad-fb67-4b82-b0d7-add06a816c45.png)

1. Create a menu with "Super + <" as shortcut in menu editor
2. The shortcut isn't indicated below the menu name.

## Expected Behavior

We should see the keyboard shortcut there, same as for other menus.

## System

 - Linux distribution: Fedora 36
 - Fly-Pie version: 16
 - GNOME Shell version: 42.3

**Comment by Schneegans** [comment]
Thanks for reporting this! It should be fixed now in the `main` branch.
