### ISSUE TITLE
Garbled text in tutorial

### ISSUE THREAD

**Issue by jle64** [Schneegans/Fly-Pie#237]
## Describe the Bug

On the last page of the tutorial, text appears garbled (spaces in the middle of words) (see capture).
![garbled_text](https://user-images.githubusercontent.com/7120882/180583037-6be0dc80-349c-414b-a4c5-d4abd4e68ad2.png)

1. Go to the last page of the tutorial
2. Not sure if relevant but have your system locale set to french

## Expected Behavior

Text shouldn't have unwanted spaces inside words.

## System
_Please complete the following information:_
 - Linux distribution: Fedora 36
 - Fly-Pie version: 16
 - GNOME Shell version: 42.3

**Comment by Schneegans** [comment]
Thanks for the report! I have "fixed" this by making the text left-aligned. If you install the latest version from GitHub, it should be fixed.
