### ISSUE TITLE
Text doesn't format correctly in Fly-Pie settings

### ISSUE THREAD

**Issue by dkvc** [Schneegans/Fly-Pie#239]
## Describe the Bug
Text doesn't format correctly in some of tutorial windows and main screen in Fly-Pie settings.
![Window 2 in Tutorial](https://user-images.githubusercontent.com/99819848/181079764-07c69302-f972-4d00-a080-c52d17551114.png)
![Window 4 in Tutorial ](https://user-images.githubusercontent.com/99819848/181079792-f8814297-eab8-4fe8-83b1-4ddaef2acfaa.png)
![Main Screen](https://user-images.githubusercontent.com/99819848/181079801-f9fc9b73-3b45-45df-80b2-6631157a4588.png)

## Steps to reproduce the behavior:
1. Go to **Tutorial**.
2. Go through the **windows shown in the screenshots.**
3. Check **Main Screen**

## Expected Behavior
Text is formatted correctly without unnecessary spaces between characters.

## System
 - Fedora Workstation 36
 - Fly Pie 16 (from GNOME Extension website)
 - GNOME Shell version: 42.3.1

**Comment by Schneegans** [comment]
Thanks for the report! This has been fixed already for #237. You can either wait for the next version to be released or install the current development version from GitHub.
