### ISSUE TITLE
Fly Pie Crashing Gnome Completely

### ISSUE THREAD

**Issue by BlackHawk185** [Schneegans/Fly-Pie#240]
Lord I've done it again

## Describe the Bug
Any attempt to use the dragging/gestures in Fly Pie causing Gnome-Shell to crash and become unresponsive, save tab switching, until restarted.

1. Create a Menu
2. Attempt to Use or Drag menu by of click and drag (I.E. Create a menu and attempt to delete by dragging causing an instant crash)

journalctl -f -o cat | grep -E 'flypie|' - Attempting to use this through TTY yields systemd-logind: got pause for 13:70

Hardware is a 2 in 1 Detachable Keyboard Tablet, Which as far as I know is running in PC Mode, with rotation locked. Keyboard is not attached during use. 
```
## System
- OS: Solus x86_64
- Host: X16
- Kernel: 5.15.50-216.current
- CPU: Intel Celeron N4020 (Z) @ 2.800GHZ
- GPU: Intel GeminiLake [UHD Graphics 600]
- Fly Pie 3 installed by Gnome Shell Extension
- GNOME Shell version: 42.3.1
```
<img src="https://user-images.githubusercontent.com/1654043/182518134-47fc1d15-9247-49b2-88e2-284ecad70cca.png" width="200" height="100" />

**Comment by BlackHawk185** [comment]
Further experimentation has shown this to be an issue with Gnome Shell's touch handling itself. Will link the new issue later for those interested. Thanks

**Comment by BlackHawk185** [comment]
> Lord I've done it again
> ## Describe the Bug
> 
> Any attempt to use the dragging/gestures in Fly Pie causing Gnome-Shell to crash and become unresponsive, save tab switching, until restarted.
> 
> Steps to reproduce the behavior:
> 
>     1. Create a Menu
> 
>     2. Attempt to Use or Drag menu by of click and drag (I.E. Create a menu and attempt to delete by dragging causing an instant crash)
> 
> 
> journalctl -f -o cat | grep -E 'flypie|' - Attempting to use this through TTY yields systemd-logind: got pause for 13:70
> 
> Hardware is a 2 in 1 Detachable Keyboard Tablet, Which as far as I know is running in PC Mode, with rotation locked. Keyboard is not attached during use.
> 
> ```
> ## System
> - OS: Solus x86_64
> - Host: X16
> - Kernel: 5.15.50-216.current
> - CPU: Intel Celeron N4020 (Z) @ 2.800GHZ
> - GPU: Intel GeminiLake [UHD Graphics 600]
> - Fly Pie 3 installed by Gnome Shell Extension
> - GNOME Shell version: 42.3.1
> ```
> 
> <img alt="" width="200" height="100" src="https://user-images.githubusercontent.com/1654043/182518134-47fc1d15-9247-49b2-88e2-284ecad70cca.png">

**Comment by BlackHawk185** [comment]
While this is apparently an issue with Gnome itself somewhat, the tutorial gestures work for whatever reason, but I can not delete gestures or use others. Reopening

**Comment by Schneegans** [comment]
Sorry for not replying earlier. Are you sure that you are running Fly-Pie 3? The current version is Fly-Pie 16...

**Comment by BlackHawk185** [comment]
Off to a good start, it is Flypie 16, I was wrong. Not sure where I pulled that number from.

**Comment by Schneegans** [comment]
Just to make sure that I understood this correctly: You are trying to drag a menu in the menu editor of Fly-Pie's settings dialog? So a more complete list of required steps would be this?
1. Open Fly-Pie's settings dialog
2. Navigate to the "Menu Editor" page
3. Click the "+" button in the top right corner
4. Select "Custom Menu", a new menu shows up in the menu grid.
5. Start dragging the newly created menu item in the menu editor.
6. Crash.

Is this correct? Have you tried switching from X11 to Wayland or the other way around? Does the issue happen on both?

**Comment by BlackHawk185** [comment]
Those are the exact steps to reproduce, and I am unable to test Wayland as it is currently unsupported by Solus OS.

**Comment by BlackHawk185** [comment]
I've gone ahead and tested this on my laptop and it works fine there, so I can confirm it is a hardware issue with the tablet. Specifically the touch input handling vs click handling on PC, if I had to guess.

**Comment by Schneegans** [comment]
Actually the menu editor is pretty unusable using touch or pen input anyways. As this should be improved, I created #269 and will close this issue here.
