### ISSUE TITLE
example menu does not open

### ISSUE THREAD

**Issue by marco-silvestri** [Schneegans/Fly-Pie#242]
## Describe the Bug
Fly-pie example menu does not open at all (not even custom menus).

1. Go to Fly-pie
2. Click on 'Open the example menu'
3. Nothing happens
4. Log
```
    ➜  ~ journalctl -f -o cat | grep -E 'flypie|'
   Ignoring length property that isn't a number at line 21, col 17
   Ignoring length property that isn't a number at line 22, col 18
   Ignoring length property that isn't a number at line 1, col 31
   Ignoring length property that isn't a number at line 21, col 17
   Ignoring length property that isn't a number at line 22, col 18
   Ignoring length property that isn't a number at line 1, col 31
   Ignoring length property that isn't a number at line 1, col 39
   Ignoring length property that isn't a number at line 1, col 31
   Ignoring length property that isn't a number at line 1, col 50
   Ignoring length property that isn't a number at line 1, col 39
```

## System
_Please complete the following information:_
 - Linux distribution Debian GNU/Linux 11 (bullseye) on x11
 - Fly-Pie version 16
 - GNOME Shell version: 3.38.5

**Comment by Schneegans** [comment]
Hi there! Thanks for the report - and sorry for not answering earlier. The error message is not very helpful but it may be related to Fly-Pie. Could you please run the command earlier? Maybe it missed an important message... So please do the steps as follows:
1. Open a terminal, run `journalctl -f -o cat | grep -E 'flypie|'`. Let it continue to run.
2. Open Fly-Pie's settings dialog
3. Navigate to the tutorial.
4. Click on the 'Open the example menu' button.
5. Hopefully something useful got printed during these steps to the terminal.
6. Copy all the stuff which got printed and post it here.

Thank you!

**Comment by marco-silvestri** [comment]
I have updated it to the latest version and it seems to work flawlessly! Thanks.

Although, before the update, the output was the one I pasted there, no changes.

**Comment by Schneegans** [comment]
Weird. Well, I am glad that it works for you now!
