### ISSUE TITLE
Value for some settings are cut off (regardless of the window size)

### ISSUE THREAD

**Issue by Leleat** [Schneegans/Fly-Pie#25]
## Describe the Bug
See screenshot. Setting: 'Icon scale'

1. Go to 'Settings' tab.
2. Click on 'Center Appearance' (for example).

## Expected Behavior
Full view of setting.

## System
_Please complete the following information:_
 - Fedora 32
 - Fly-Pie version: Can't find it in the settings but the current one from extensions.gnome
 - Gnome Shell version: 3.36.6

![Screenshot](https://user-images.githubusercontent.com/53054301/93600555-5d695a80-f9af-11ea-918a-66336e86c3cc.png)

**Comment by Schneegans** [comment]
Which GTK-Theme are you using? I looks good on my end with all themes I tried :smile:

**Comment by Leleat** [comment]
> Which GTK-Theme are you using? I looks good on my end with all themes I tried smile

I am using Vimix but switching to Adwaita fixed it. So I am closing this issue.
