### ISSUE TITLE
Usage of environment variable expansion on command field of FlyPie elements

### ISSUE THREAD

**Issue by D3vil0p3r** [Schneegans/Fly-Pie#250]
## The Motivation
It could be useful if inside the command field of a FlyPie element it is possible to use environment variables to be expanded in order to make calls to these elements more general purpose. For example, I'm using Kitty terminal and I would like to call a CLI tool and, after the call, keep the terminal opened. For doing it, I can use the following command inside the "Command" field:
```
kitty /usr/bin/bash -c "nmap;/usr/bin/bash;"
```
This command will open Kitty terminal for running Nmap tool and then keeping the terminal shell by calling Bash.

In case I would like to change the Shell of my system, for example I would like to use Fish or Zsh shell, a general purpose solution could be using $SHELL environment variable. So, our command will be:
```
kitty $SHELL -c "nmap;$SHELL;"
```
In this case, I get the error:
```
Failed to launch child: $SHELL
With error: No such file or directory
Press Enter to exit.
```
It means that the first `$SHELL` variable is not expanded (even if I use double quotes around it). Only the environment variables inside the `-c` arguments are expanded according to other tests.

Is it possible to improve FlyPie in order to expand environment variables written in Command field?

## The Solution
What I expect from the solution is that the environment variable is expanded. For example, if I use Zsh as shell, and in the Command field I have:
```
kitty $SHELL -c "nmap;$SHELL;"
```
It should be run like `kitty /usr/bin/zsh -c "nmap;/usr/bin/zsh;"`.

## The Alternatives
A current alternative solution is a little uncomfortable because it is a script that detect the kind of current new Shell, for example fish, then
```
dconf dump /org/gnome/shell/extensions/flypie/ > ~/temp.txt
sed -i 's/zsh/fish/g' ~/temp.txt
dconf load /org/gnome/shell/extensions/flypie/ < ~/temp.txt
rm -rf ~/temp.txt
```

**Comment by Schneegans** [comment]
Hi there! Sorry for the late reply... (I was busy learning RUST to create a new RSS reader :wink:). I am not sure if there is an easy way to add environment variable expansion there. However, you may try to wrap your entire command in a `/bin/bash -c ...`. This way, bash will expand the variable. For me, this does work as expected (it runs `glxgears` in a newl opened terminal using `zsh` in my case):

`/bin/bash -c "gnome-terminal -- $SHELL -c glxgears"`

**Comment by Schneegans** [comment]
Sorry for my ignorance, but doesn't this wrapping solve your issue? `bash` is only invoked to expand the `$SHELL` variable; inside of `kitty` the user's shell will be used. So the full command would be

```bash
/bin/bash -c 'kitty $SHELL -c "nmap;$SHELL;"'
```

I just tested this and it does work nicely...

**Comment by D3vil0p3r** [comment]
> Sorry for my ignorance, but doesn't this wrapping solve your issue? `bash` is only invoked to expand the `$SHELL` variable; inside of `kitty` the user's shell will be used. So the full command would be
> 
> ```shell
> /bin/bash -c 'kitty $SHELL -c "nmap;$SHELL;"'
> ```
> 
> I just tested this and it does work nicely...

The wrapping worked well. What I would like to have is the following:
```
kitty $SHELL -c -c "nmap;$SHELL;"
```
because if the user, during the installation of my system, chooses zsh as shell, FlyPie should have the following command:
```
kitty /bin/zsh -c "nmap;/bin/zsh;"'
```
because if the user chooses zsh, bash will be uninstalled from the system. If it is not clear, I can reach you on Matrix

**Comment by D3vil0p3r** [comment]
> Ah, I see. So the problem is that `bash` is not available anymore if the user chose another shell. But some basic shell should be available on the system, shouldn't it? The same command works with `/bin/sh` which should be installed, I guess? Else nearly no shell scripts would be working. Most of them will use either `#!/bin/sh` or `#!/bin/bash`...
> 
> PS: For learning RUST, I am currently primarily using [this](https://doc.rust-lang.org/rust-by-example/) and [that](https://gtk-rs.org/gtk4-rs/git/book/) 😄.

Yes it is right. I didn't think about `/bin/sh` and I think it could fit well with my needs. Thank you also for the RUST links ^^
