### ISSUE TITLE
Creation of pacman package for Arch Linux

### ISSUE THREAD

**Issue by D3vil0p3r** [Schneegans/Fly-Pie#251]
## The Motivation
It could be a good idea having a package that could be retrieved by Arch Linux repositories (like AUR) that allow Arch users to install FlyPie menu by `sudo pacman -S <package-name>

## The Solution
I implemented a `PKGBUILD` file for reaching this purpose:
```
pkgname=gnome-shell-extension-flypie-git
pkgdesc="Fly-Pie - an innovative marking menu written as a GNOME Shell extension."
pkgver=r1530.dafe2af
pkgrel=1
_gitname=Fly-Pie
arch=('any')
url="https://github.com/Schneegans/Fly-Pie"
license=("GPLv3")
install="flypie.install"
depends=('gnome-shell')
makedepends=('make' 'git' 'unzip')

_dir="${_gitname}"
source=("git+https://github.com/Schneegans/Fly-Pie.git")
sha256sums=("SKIP")

pkgver() {
    cd "${srcdir}/${_dir}"
    printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

package() {
    
    mkdir -p "${pkgdir}/usr/share/gnome-shell/extensions/flypie@schneegans.github.com"
   
    cd "${srcdir}/${_dir}"
    make zip
    unzip "${srcdir}/${_dir}/flypie@schneegans.github.com.zip" -d "${pkgdir}/usr/share/gnome-shell/extensions/flypie@schneegans.github.com/"

    install -Dm644 "${srcdir}/${_dir}/schemas/org.gnome.shell.extensions.flypie.gschema.xml" -t "${pkgdir}/usr/share/glib-2.0/schemas"
}
```
Along with this `PKGBUILD`, a post install/upgrade/remove install is also written, called `flypie.install:
```
post_install() {
    echo
    echo "$(tput bold)At the end, reboot and then run: gnome-extensions enable flypie@schneegans.github.com$(tput sgr0)"
    echo
}

post_upgrade() {
    post_install
}

post_remove() {
    echo
    echo "$(tput bold)At the end, run: gnome-extensions uninstall flypie@schneegans.github.com$(tput sgr0)"
    echo
}
```
If these two files are uploaded and maintained on one Arch repository (like Chaotic-AUR), the user can install Fly-Pie by simply running:
```
sudo pacman -S gnome-shell-extension-flypie-git
<reboot or logout/login>
gnome-extensions enable flypie@schneegans.github.com
``` 
This is useful mostly in the cases a OS dev would like to install Fly-Pie during the creation of an ISO or the installation of the OS (Arch-based)

For uninstalling:
```
sudo pacman -R gnome-shell-extension-flypie-git

gnome-extensions uninstall flypie@schneegans.github.com
```

**Comment by Schneegans** [comment]
Hey there! This seems like a good idea. I do not know much about Arch, but I know that there are already these two:

* https://aur.archlinux.org/packages/gnome-shell-extensions-fly-pie
* https://aur.archlinux.org/packages/gnome-shell-extensions-fly-pie-git

Do they provide a similar functionality?

**Comment by D3vil0p3r** [comment]
> Hey there! This seems like a good idea. I do not know much about Arch, but I know that there are already these two:
> 
> * https://aur.archlinux.org/packages/gnome-shell-extensions-fly-pie
> * https://aur.archlinux.org/packages/gnome-shell-extensions-fly-pie-git
> 
> Do they provide a similar functionality?

I didn't notice it. But yes, it is the same functionality. Could you please insert these two AUR packages in your README in a section like "Arch Linux Install"?
