### ISSUE TITLE
Super-RMB stops working after some usage

### ISSUE THREAD

**Issue by Leleat** [Schneegans/Fly-Pie#254]
## Describe the Bug

Usually, Super-RMB opens Fly-Pie. After some time however a Super-RMB doesn't do anything and all subsequent Super-RMBs open the default GNOME window menu. Here is a screenrecording (the simulated shortcut maximizes the window the first time)

[Screencast from 2022-11-18 21-09-46.webm](https://user-images.githubusercontent.com/53054301/202794272-3174be73-13ff-4569-8012-af9099636e35.webm)

**STR**

Unfortunately, I can't reproduce it every time I use super-rmb. It just happens when using the Super-RMB activation *at some point*. It appears to be related to the `Display Timeout` setting. I can't reproduce it with a delay of 0. But with a delay of about 200 ms I can usually trigger it by spamming super-rmb in a few seconds. I can also reproduce it with all other extensions disabled. There is nothing in journalctl.

## Expected Behavior

Super-RMB should still be working :)

## System
_Please complete the following information:_
 - Fedora 37
 - Fly-Pie version 17 (EGO)
 - GNOME Shell version: 43.0

**Comment by Schneegans** [comment]
Thanks for the report! I can indeed reproduce this. I'll see if I find the reason :smile:

**Comment by Schneegans** [comment]
This was a really hard to find bug. In fact, it could not only be triggered by Super+RMB activation but also by normal hotkey activation. Just spamming the configured hotkey with a display timout > 0 could make Fly-Pie completely unresponsive until the session is restarted.

Anyway, I think it should work now!
