### ISSUE TITLE
Tutorial videos don't show on Ubuntu 22.04

### ISSUE THREAD

**Issue by jvalrog** [Schneegans/Fly-Pie#258]
## Describe the Bug
Tutorial videos don't show.

![image](https://user-images.githubusercontent.com/456311/209429932-c90d395e-393a-4f3a-affa-c38b1cd5c163.png)

## System
Ubuntu 22.04
Gnome Shell 42.5
Fly-Pie 17

**Comment by Schneegans** [comment]
Thanks for the report! I think you may have to install the package `libgtk-4-media-gstreamer`. Does this help?

**Comment by Schneegans** [comment]
Any news on this one? Does this work?

**Comment by jvalrog** [comment]
> Any news on this one? Does this work?

Yeah sorry, couldn't reply before. That fixed it, thanks!

**Comment by gdelfino** [comment]
I just had the same issue with Pop!_OS 22.04. After installing libgtk-4-media-gstreamer I can now see the video but not correctly. It is horizontally compressed to about 1/4 of the correct width. The other 3/4 of the video shows up black.
