### ISSUE TITLE
Super key as binding

### ISSUE THREAD

**Issue by dillongeary** [Schneegans/Fly-Pie#259]
Currently, the super key only counts as a "modifier" for a binding (i.e. you can do Super + e) but there isn't any support for the Super key on its own to be a binding. It would be really cool to allow the Super key (or any "modifier" keys) to become bindings on their own!

I'm looking at fly-pie to replace my current Super menu, but having to do some complex key press to open it doesn't really work for me (and yes, two keys is a complex key press to me hehe)

**Comment by Schneegans** [comment]
Thanks for the suggestion! When I find the time, I'll look into this but I doubt that it is possible as a single press of <kbd>Super</kbd> is already captured by Mutter before it is sent to client windows.

As a workaround, you could try to remap your keys with something like [input remapper](https://github.com/sezanzeb/input-remapper/).

**Comment by Schneegans** [comment]
I tested some approaches but I think that this is not possible without remapping the underlying key value. `Meta.Display.grab_accelerator` does not allow binding of modifier-only accelerators. So I think that there is nothing we can do about this...
