### ISSUE TITLE
Allow Partial Pie

### ISSUE THREAD

**Issue by Leleat** [Schneegans/Fly-Pie#26]
## The Problem
I'd like to use Fly Pie as a mouse-only launcher. So I followed the suggestion in the README and put the activation in hot corner (bottom right). This makes submenus, which are in the direction of the corner, awkward to navigate. 1. because they are so cramped in the corner. And 2. because I have a rather large monitor, so I need to make a large wrist movement to reach the bottom right corner. Then, to navigate to apps/submenus on the right side and at the bottom I need to reset my wrist/mouse. Activating the setting "open in screen center" solves the first problem but not the second one.

## The Solution
Allow partial pies. This way I can flick to the bottom right with my wrist to activate the fly pie and flick back (to the top/left) to navigate through it.

## The Alternatives
None. The way it is currently, it works, just a bit awkward. So this is really just a minor QoL feature for me.

**Comment by Schneegans** [comment]
Have you tried setting the "Fixed Angles" of the items? This could be a solution for your use-case!

**Comment by Leleat** [comment]
After playing around with it a bit, it seems to work reliably. So I am closing the issue, thanks.
