### ISSUE TITLE
Pie menu not visible above fullscreen applications

### ISSUE THREAD

**Issue by RickDW** [Schneegans/Fly-Pie#263]
Whenever I try to use Fly-Pie in an application in fullscreen mode (e.g. the pdf reader Okular or Firefox) the pie menu does not become visible. The menu does still work however, so I can still make marks with my mouse for example. 

**System spec:**
Ubuntu 22.04
Fly-Pie 17
GNOME version 42.5 on Wayland

**Comment by Schneegans** [comment]
Thanks for the report! I think this only happens on Wayland, doesn't it? I'll see whether I can fix this, but it may take some time as I am currently busy with a major refactoring of the Burn-My-Windows extension...

**Comment by RickDW** [comment]
I'm not sure if it happens on X11 as well, I only run Wayland. 
Sounds good, just take your time!

**Comment by RickDW** [comment]
I was forced to switch to X11 for unrelated reasons, and the bug doesn't show up anymore now. So it seems like a wayland issue, at least on my system.

**Comment by Schneegans** [comment]
I think I found the issue. If you want to, you could [test the latest version from git](https://github.com/Schneegans/Fly-Pie/blob/main/docs/installation.md#c-cloning-the-latest-version-with-git).

**Comment by RickDW** [comment]
Nice work! - I'm unfortunately not able to test it because all of my systems run on X11 at the moment, but it's good to know it works if I need to switch back at some point :)
