### ISSUE TITLE
Make Fly-Pie usable with "Animations Disabled"

### ISSUE THREAD

**Issue by Schneegans** [Schneegans/Fly-Pie#27]
Currently, if animations are globally disabled in GNOME Shell, Fly-Pie is hardly usable. It should be possible to use Fly-Pie even if animations are disabled.

**Comment by Schneegans** [comment]
Making it usable seems difficult. I have added a warning which allows users to enable animations if they happen to be disabled.

**Comment by genodeftest** [comment]
Interestingly, it works fine for me with animations disabled (GNOME shell 41.1.1 on wayland / Fedora). I wonder if the warning is still necessary?

**Comment by Schneegans** [comment]
Rescheduled to Fly-Pie 14, as Fly-Pie 13 will be released soon because it includes an important bug fix.
