### ISSUE TITLE
Block the opening of the menu when a specific application is focused

### ISSUE THREAD

**Issue by SandResidence** [Schneegans/Fly-Pie#275]
## The Motivation
When I play a game (in my case Minecraft), almost every now I click Ctrl + Space and a menu opens.

## The Solution
I would like it to be possible to specify specific applications that would prevent the menu from being opened when focused.

## The Alternatives
No idea.

**Comment by Schneegans** [comment]
Hi there! Thanks for the suggestion. I think that this will be solved by #153. However, I currently have not the time to implement this (but it is still planned :smile:). 

For now, you could assign a shortcut for enabling / disabling the extension altogether. Just add two custom shortcuts in your system keyboard settings which execute `gnome-extensions enable flypie@schneegans.github.com` and `gnome-extensions disable flypie@schneegans.github.com` respectively.

With a bit of bash scripting you could also manage to create a script which _toggles_ the extension and then bind this to a hotkey, I guess...
