### ISSUE TITLE
Fly-Pie Menu not showing icons consistently

### ISSUE THREAD

**Issue by hendersj** [Schneegans/Fly-Pie#283]
## Describe the Bug
In the actual Fly-Pie menu, images are not displayed for items I created (the settings gear does show).  In the configuration utility, the images are shown.

Menu pop-up:
![image](https://user-images.githubusercontent.com/2662071/228389262-ed9d4676-e863-42cf-8c1f-9788e44b87ce.png)

Configuration screen:
![image](https://user-images.githubusercontent.com/2662071/228389178-f2614fcc-7bd8-4f54-b01a-c529f0c8e64a.png)

1. Open the menu using Super+Right Mouse Button
2. Note that the menu isn't showing the images
3. Open the configuration tool using the gear option in the menu
4. Note that the menu configuration shows the images

There's no log output using the journalctl command related to flypie.

## Expected Behavior
The icons should show the graphics rather than the icon name as shown in the screenshots.

## System
_Please complete the following information:_
 - Linux distribution: openSUSE Tumbleweed 20230326
 - Fly-Pie version: 18
 - GNOME Shell version: 44.0

**Comment by Schneegans** [comment]
Hey there, thanks for the report! There landed some changes in GNOME 44 recently which changed how icons are loaded (previously this was done using GTK3, now it uses some custom code). This seems to affect Fly-Pie and I can indeed reproduce this.

I'll see if I find a solution!

**Comment by hendersj** [comment]
Excellent, thanks!  Let me know if there's anything else I can provide.

**Comment by Schneegans** [comment]
This should be fixed in the current `main` branch! Now you either have to wait for the next release or build the extension from source :wink:

**Comment by hendersj** [comment]
Thanks - appreciate the quick fix.  I will look to pull down the code and build it locally until the next release is avaialble.

**Comment by hendersj** [comment]
Just FYI, I saw that the update is now released, and it works perfectly here.  Thanks again for the quick resolution!
