### ISSUE TITLE
Part of achievement notifications not translated

### ISSUE THREAD

**Issue by flipflop97** [Schneegans/Fly-Pie#288]
## Describe the Bug

Part of the achievement notification text is not translated, while this translation exists in the current release. For example the notification below, where only the achievement name is translated but the rest isn't.

![afbeelding](https://user-images.githubusercontent.com/13943260/229349707-c43a93f4-e4df-4c79-89f2-5e314274223b.png)

1. Set language to any fully translated one (Dutch in my case)
2. Trigger an achievement notification

## Expected Behavior
The notification should be fully translated, but it isn't.

## System
 - Arch Linux
 - Fly-Pie version 19
 - GNOME Shell version: 44.0

**Comment by Schneegans** [comment]
Good catch! Thank you for submitting this report. I just found the reason and fixed it in the `main` branch.
