### ISSUE TITLE
Shortcuts don't seem to work on Fedora 38

### ISSUE THREAD

**Issue by Leleat** [Schneegans/Fly-Pie#295]
## Describe the Bug

I have menus that simulate `Super`+`up` and `Super`+`q`. When activating those, nothing happens on my new install of Fedora 38. It worked on Fedora 37 (or maybe I was on 36.... not so sure anymore 😅).

1. Be on Fedora 38
2. Activate an item that simulates a shortcut
3. Nothing happens

Running `journalctl -fo cat /usr/bin/gnome-shell` produces the following when trying to activate an item:

```
Window manager warning: Overwriting existing binding of keysym ff53 with keysym ff53 (keycode 72).
```

## Expected Behavior

The shortcut should be simulated.

## System

 - Fedora 38
 - Fly-Pie version 19 (from EGO)
 - GNOME Shell version: 44.0

---

It appears GNOME Shell/Fly Pie now uses GTK4. So the cause for this bug appears to be https://github.com/Schneegans/Fly-Pie/blob/main/src/common/InputManipulator.js#L58. The first value of the returned array is a 'success' bool. Fixing that makes Fly Pie work again. I didn't open a PR though because I don't know if there are potentially other GTK3 vs 4 issues going on.

**Comment by Schneegans** [comment]
Hey there, thanks a lot for the report! And thank you even more for discovering the fix! There were indeed some more issues. I hope that everything is working now again. I'll soon release a new version on ego.
