### ISSUE TITLE
Cannot resize settings screen

### ISSUE THREAD

**Issue by blacklightpy** [Schneegans/Fly-Pie#296]
## Describe the Bug
The settings screen is too big for my screen and I cannot scale it. My resolution is 1366x768, and it looks like it expects 1080p at least.

I tried 800x600 too, and I could see that the window keeps a fixed resolution.

1. Install extension
2. Open extension settings in Extension Manager

## Expected Behavior
I can resize the window.

## System
_Please complete the following information:_
 - Linux distribution: OpenSUSE Tumbleweed
 - Fly-Pie version: 19
 - GNOME Shell version: 44

**Comment by Schneegans** [comment]
Thanks for the report! Once I find the time, I'll look into it. It should be fixable by scattering a couple of `Gtk.ScrolledWindow`s throughout the settings dialog :smile:.
