### ISSUE TITLE
Export/Import configuration settings?

### ISSUE THREAD

**Issue by Rmano** [Schneegans/Fly-Pie#30]
## The Problem
I have configured the (great!!! 🚀) Fly-Pie on one of several computers. I'd like to have an "export/import configuration" for the extension... I do not know if it's possible now; I didn't find a straightforward way for now.

## The Solution
In `Settings`, a menu or button that saves all the configurations, and a correspondent menu or button to load a configuration file.

## The Alternatives
Re-configure the extension manually on every machine. But I have three of them... ;-)

**Comment by Schneegans** [comment]
This is indeed a great idea! I will schedule this for the next version. Until then, you can use `dconf-editor` and simply copy the contents of the key `/org/gnome/shell/extensions/flypie/menu-configuration` to your other machines. The changes will be applied immediately!

**Comment by Schneegans** [comment]
You can also do the backup with the command line. Use the following to store the menu configuration in a file called `menu.json`:
```bash
dconf read /org/gnome/shell/extensions/flypie/menu-configuration > menu.json
```

Then you can load the configuration with:
```bash
dconf write /org/gnome/shell/extensions/flypie/menu-configuration "`cat menu.json`"
```

**Comment by Schneegans** [comment]
I just implemented the functionality. If you want to, you can use the current develop branch to test the new feature!

![Screenshot](https://user-images.githubusercontent.com/829942/96351434-8880c000-10bb-11eb-8275-655aa760c467.jpg)
