### ISSUE TITLE
KDE

### ISSUE THREAD

**Issue by iomari** [Schneegans/Fly-Pie#307]
Greetings,
will Fly-Pie ever work with KDE or should I just forget about it?

**Comment by Schneegans** [comment]
Fly-Pie will never work on KDE. However, I am currently working on a platform independent successor project! You can follow and support the development on Ko-fi: https://ko-fi.com/schneegans

Here was the initial announcement: https://ko-fi.com/post/Introducing-Ken-Do-L3L7L0FQ2

**Comment by iomari** [comment]
Thank you for the quick reply
