### ISSUE TITLE
problem with the text inserter in wayland

### ISSUE THREAD

**Issue by AngelBrielez** [Schneegans/Fly-Pie#315]
## Describe the Bug
Hi, flypie has a problem with the text inserter in wayland, it doesn't paste the text as it should, it just doesn't do anything. please i would love if you could fix this problem, because it helps me a lot in my work. thank you very much.

1. Go to 'Text Inserter'.
2. Click on 'Text programmed in the text inserter'.
3. Does nothing

## Expected Behavior
Paste the programmed text into flypie.

## System
_Please complete the following information:_
 - Linux distribution [Ubuntu 23.04]
 - Fly-Pie version [21]
 - GNOME Shell version: [44.3]

**Comment by Schneegans** [comment]
Hi there! Thanks for the report. For me, it currently does work neither Wayland nor on X11 :sweat_smile: 

I'll see if I find the reason... It could take some time, as I am currently very busy with the ESM ports of my extensions for GNOME 45.
