### ISSUE TITLE
Macros, or multi-key hotkeys

### ISSUE THREAD

**Issue by Jawsingale** [Schneegans/Fly-Pie#33]
Trying to work in Houdini or other applications which I normally use the wacom software for, on windows or mac, I miss the ability to write macros, or multihotkeys.  Example,  <Tab> <W> <R> <A> <Shift> <Enter>.   So this would hit tab, type wra then hit shift enter.  I use this frequently for houdini + wacom pad.  Potentially a way also to add a timer between each key, so you could say, hit Tab, wait 1 second, then enter the rest in, etc.

I tried looking around the repo but I am too new to programming to add something like this.

Thanks :D

**Comment by Schneegans** [comment]
This is indeed a great idea and could replace the "Insert-Text"-item. But I think that it's rather complicated to implement. I'll think about it and post any news here in this issue! Thank you!

**Comment by Schneegans** [comment]
Rescheduled to Fly-Pie 14, as Fly-Pie 13 will be released soon because it includes an important bug fix.

**Comment by Schneegans** [comment]
Rescheduled again as Fly-Pie 14 will focus on GNOME 42 support...

**Comment by Schneegans** [comment]
I fear that I won't be able to work on this anytime soon as I am pretty busy with Burn-My-Windows currently...

**Comment by Schneegans** [comment]
I will not add this feature to Fly-Pie as I am currently focusing on the successor project [Kando](https://github.com/kando-menu/kando). Macros are already more or less support by the Kando prototype and will become a core part in the future!
