### ISSUE TITLE
Is it available for Kde , i am using kubuntu.

### ISSUE THREAD

**Issue by gammer1608** [Schneegans/Fly-Pie#334]
Is it available for Kde , i am using kubuntu.

**Comment by Schneegans** [comment]
Fly-Pie is only available for GNOME. However, I am currently working on its cross-platform successor [Kando](https://github.com/kando-menu/kando), which also supports KDE. You can follow its progress and support the project on [my Ko-fi page](https://ko-fi.com/schneegans) :wink:.
