### ISSUE TITLE
Hold a single key

### ISSUE THREAD

**Issue by oredaze** [Schneegans/Fly-Pie#343]
Right now we have the ability to press a key combination, for example Ctrl + space, release space and hold Ctrl, drag an item in the menu and release Ctrl to activate.

It would be super nice if we could do that for a single key (hold without modifiers). This way I can bind it to a side mouse button to achieve the hold functionality without reaching for the keyboard.

**Comment by oredaze** [comment]
Actually forget it. I will wait for Kando to iron out things.

**Comment by Schneegans** [comment]
Until then, you could try using [xbindkeys](https://www.linuxuprising.com/2019/11/how-to-bind-mouse-buttons-to-keyboard.html) or [input-remapper](https://github.com/sezanzeb/input-remapper). The former only works on X11, the latter also supports Wayland. :smile:
