### ISSUE TITLE
A Submenu where we can search for our term in specific website

### ISSUE THREAD

**Issue by Shahin-rmz** [Schneegans/Fly-Pie#347]
## The Motivation  
There are cases, which the user wants to search for a term in specific website and get the quick result.

## The Solution  
In some launchers, there is possibility to type what you want in text box, and it will search for the term in your preferred website. I have some examples here. 
We can have a sub menu where we can click on, and then a text box opens up and when we type, it searches for our term in that website. 

## The Alternatives  
Here is how my setting in uLauncher looks like
![image](https://github.com/Schneegans/Fly-Pie/assets/32805117/50465714-6366-4d46-9b66-dbf88426feeb)

**Comment by Schneegans** [comment]
Thanks again. However, as I metioned in #346, Fly-Pie is currently in low-maintenance mode as I am investing most of the little spare time I have into its successor project, [Kando](https://github.com/kando-menu/kando). So I personally will not implement new features for Fly-Pie these days.

Also, Fly-Pie is a mouse- or touch-based tool, so if you want to search for something with your keyboard, maybe other tools are better suited. That being said, I'll keep this open to see if maybe others are interested.

**Comment by Shahin-rmz** [comment]
I have made a small workaround for the process.
It looks like that. 
![image](https://github.com/Schneegans/Fly-Pie/assets/32805117/104878e5-30e1-4538-af6c-1311da163fb3)
Inside Fly Pie, I launch ULauncher and then type what I want inside that. It works, but it's not the best option, because I have 3 Launchers  now :) Fly Pie for when I work touch intensive works, ULauncher for searching inside Fly Pie and Rofi for when I work Keyboard intensive works.

> Thanks again. However, as I metioned in https://github.com/Schneegans/Fly-Pie/discussions/346, Fly-Pie is currently in low-maintenance mode as I am investing most of the little spare time I have into its successor project, [Kando](https://github.com/kando-menu/kando). So I personally will not implement new features for Fly-Pie these days.
 
Really appreciate the idea of Gnome Pie and Fly pie. Love to see Kando. It looks very promising and would love to work with that. Thanks for developing and maintaining such a nice piece of code.

> Also, Fly-Pie is a mouse- or touch-based tool, so if you want to search for something with your keyboard, maybe other tools are better suited. That being said, I'll keep this open to see if maybe others are interested.

Of course. Actually my use case is when I study something, or work with some patients data, when taking note, be able to search for some details in medical encyclopedias. It helps me to be much more productive. Also because of the sensitivity of the data I always work with Open Source and stable apps like Fly Pie.
Thanks for making the world better place.

**Comment by Schneegans** [comment]
Closing this as it's most likely not going to be added to Fly-Pie.
