### ISSUE TITLE
.desktop files as support in Actions section

### ISSUE THREAD

**Issue by D3vil0p3r** [Schneegans/Fly-Pie#352]
## The Motivation
.desktop files already contain code to execute a specific application and set the related icon. Usually they are shown on Linux menus but it could be very comfortable to have the possibility to add an item like desktop file in order to show it directly in the FlyPie menu without specifying exec and icon because they are already specified in the .desktop file itself.

## The Solution
Integrate the possibility to insert a .desktop application file in FlyPie menu. FlyPie menu could go to check the `/usr/share/applications` or `$HOME/.local/share/applications` to automatically detect .desktop app files to choose.

**Comment by Schneegans** [comment]
Hi there! This is already possible: If you add a "Launch Application" action, there is a small ... button next to the command field. If you click this, Fly-Pie lists all installed applications. The apps in this menu come from the desktop files of your system!

**Comment by D3vil0p3r** [comment]
Oh very nice! Thank you!

**Comment by Schneegans** [comment]
Anyway, thanks for the report! This just made me realize that dragging `*.desktop` files to the menu editor did not work anymore on GNOME 45 (and maybe also earlier). I just pushed a fix to the `main` branch to resolve this issue! So you can now also drag `*.desktop` files to the menu editor!
