### ISSUE TITLE
Add more checks?

### ISSUE THREAD

**Issue by daPhipz** [Schneegans/Fly-Pie#39]
When working on the Shell scripts in this repo, I noticed that the `shellcheck` addon in my VS code complained about some errors/potential issues with the file. This got me thinking about adding some tests.
Do you think we should...

1. ...run `shellcheck` as part of the `tests` workflow to ensure nothing bad happens?
2. ...add a functionality test to both shell scripts (check if all files are created correctly, for example; and check the error conditions)?
3. ...add a Markdown linter check?

The last one is often personal taste, I know ;) but I think checking the shell scripts is definitely worth it.

as a little example, here are the errors and warnings that `shellcheck` throws at me when running it against `compile_locales.sh`:

```bash
$ shellcheck compile_locales.sh

In ./compile-locales.sh line 23:
for FILE in `ls $FLYPIE/po/*.po`
            ^------------------^ SC2045: Iterating over ls output is fragile. Use globs.
            ^------------------^ SC2006: Use $(...) notation instead of legacy backticked `...`.
                ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
for FILE in $(ls "$FLYPIE"/po/*.po)


In ./compile-locales.sh line 31:
  mkdir -p $FLYPIE/locale/$LANGUAGE/LC_MESSAGES
           ^-----^ SC2086: Double quote to prevent globbing and word splitting.
                          ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
  mkdir -p "$FLYPIE"/locale/"$LANGUAGE"/LC_MESSAGES


In ./compile-locales.sh line 32:
  msgfmt $FILE -o $FLYPIE/locale/$LANGUAGE/LC_MESSAGES/flypie.mo
         ^---^ SC2086: Double quote to prevent globbing and word splitting.
                  ^-----^ SC2086: Double quote to prevent globbing and word splitting.
                                 ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
  msgfmt "$FILE" -o "$FLYPIE"/locale/"$LANGUAGE"/LC_MESSAGES/flypie.mo

For more information:
  https://www.shellcheck.net/wiki/SC2045 -- Iterating over ls output is fragi...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
  https://www.shellcheck.net/wiki/SC2006 -- Use $(...) notation instead of le...
```

**Comment by Schneegans** [comment]
Why not? Tests are always good to have, especially if they can be run by CI jobs. I see that you already started working on this, great! And I realized that the Badges Workflow fails... I'll fix this in a minute!

**Comment by Schneegans** [comment]
The Badges should work again...

**Comment by daPhipz** [comment]
Thanks for your encouragement! I'm still somewhat new to the coding business, your open and friendly way of communicating means a lot to me.
I am using Linux since around 2014 though, so I know my "advanced" way around computers - which makes me somewhat less of a noob, I guess xD

How about introducing a new emoji for working on tests themselves and making changes in the code in order to satisfy them?
Like ✔, for example? Or do you think the :wrench: is good enough for that

**Comment by Schneegans** [comment]
Your interest in this project also mean a lot for me :smiley: !

That's a good idea! In another project I used :green_heart:; [gitmoji](https://gitmoji.carloscuesta.me/) suggests :white_check_mark: for this purpose. But personally I like your suggestion of :heavy_check_mark: more. We should go for this! You can add this to CONTRIBUTING.md!

**Comment by Schneegans** [comment]
BTW, from my experience, playing with Github Actions will require that you make _a lot_ of commits. Do not hesitate to create a PR with many commits, I will just do a _squash merge_ in this case!

**Comment by daPhipz** [comment]
I will close this issue, since there's now a PR #42 where we can discuss things as we go on.
