### ISSUE TITLE
Add CI Test for application building?

### ISSUE THREAD

**Issue by daPhipz** [Schneegans/Fly-Pie#45]
I think it would be beneficial if we had a CI test that would build the extension and check if it builds correctly.

I am not sure how this can be done in a meaningful way (not just replicating `.github/workflows/deploy.yml` and watch for errors - or is that sufficient?).
Is there a way to examine the created `.zip` file if everything works as it should and a working extension was produced?

**Comment by Schneegans** [comment]
I think one easy thing would be to put the shell code from `.github/workflows/deploy.yml` to a script (e.g. `create-release.sh`), which could then be executed as part of the checks. This would prevent us from duplicating the code.

Testing the bundled extension will be difficult. I think it would be too complex to try installing GNOME-Shell on the CI nodes! A better approach would be to add unit tests for individual parts of the code. But I am not sure how this can be done with GJS! I doubt that conventional JavaScript testing frameworks like [jest](https://jestjs.io/) will work.

For a small software project like Fly-Pie we could also create our own small test suite and run it with `gjs`. But one major issue will be that a lot of the code is actually expected to run the process of GNOME Shell: Therefore several modules will not be available at test time... I'll have to think about this a bit more...

**Comment by daPhipz** [comment]
> I think one easy thing would be to put the shell code from .github/workflows/deploy.yml to a script (e.g. create-release.sh), which could then be executed as part of the checks.

I will submit a PR right now.

> I think it would be too complex to try installing GNOME-Shell on the CI nodes! A better approach would be to add unit tests for individual parts of the code.

Yes, that was my thought as well. Better make sure that all the small parts work and do the "real life" testing on our machines, with the installed extension.

**Comment by daPhipz** [comment]
Closing this, since we discuss it over at the PR ;)
