### ISSUE TITLE
Add Release-Zip-Size-Check

### ISSUE THREAD

**Issue by Schneegans** [Schneegans/Fly-Pie#56]
When uploading Fly-Pie 4 to extensions.gnome.org, I received the warning that 4.4 MB is too large. I haven't found any documentation on the allowed maximum but I re-tried the upload without the README-Title-Gif. This resulted in around 3.6 MB which was accepted. So I guess that the limit is around 4 MB (maybe 4096 KB?).

It would be cool if our `Check if Fly-Pie builds correctly` would check this limit!

**Comment by Schneegans** [comment]
@daPhipz would you like to look into this?

**Comment by daPhipz** [comment]
Will do!
