### ISSUE TITLE
Remove unnecessary Files from the Release-Zip

### ISSUE THREAD

**Issue by Schneegans** [Schneegans/Fly-Pie#57]
This is related to #56. We have to assure that the release zip stays below a certain file size limit. I think we could move the `CONTRIBUTING.md` and the images required for the `README.md` to a separate `docs/` directory which is not included in the zip. This would save ~1.2 MB. We could also remove the `README.md` from the zip file as we always directly link to the GitHub page anyways.

**Comment by Schneegans** [comment]
@daPhipz would you like to look into this?

**Comment by daPhipz** [comment]
Will do!

**Comment by daPhipz** [comment]
Everything in the `/resources` directory apart from the GIFs is only used in the `README` - is this correct? (just double-checking, in case I missed something :wink:)

**Comment by Schneegans** [comment]
Only `tutorial1.gif`, `tutorial2.gif`, and `tutorial3.gif` are required for the release-zip. I think all others can be moved to a `docs/` directory!
