### ISSUE TITLE
Make some GtkPopovers automatically disappear

### ISSUE THREAD

**Issue by daPhipz** [Schneegans/Fly-Pie#63]
While playing around with `glade`, I noticed that the `preset-popover` and the `item-application-popover` do not disappear when an item is chosen from the list, unlike the `item-type-popover` that is shown when the user adds an item to a menu.

IMO, it would be a better experience when these two popovers would disappear once an item is selected. What do you think?

**Comment by Schneegans** [comment]
I partially agree. The `item-application-popover` should definitely disappear (btw, it hides on double click currently), but regarding the `preset-popover` I am not totally sure as a common use-case is to test different presets (there will be more in the future!). Maybe this could be hidden on double-click?

**Comment by daPhipz** [comment]
Ah yes, you make a good point here. Didn't think of that.

I think closing the `preset-popover` on a double click is a good solution!
We should keep the `item-application-popover` at double click to close as well, for consistency.

**Comment by daPhipz** [comment]
On the other hand, no - I think once you click on an application, you definitely want to use it... There is no use to the in-between state of the item being selected, but no action taken. Forget about the consistency part 😂

**Comment by Schneegans** [comment]
I think it should depend on the most common use case. It's also difficult to decide for the `icon-select-popover`...

**Comment by daPhipz** [comment]
Yeah, you're right...
Is there some documentation that suggests a default behavior? I will have a look today if I can find any information on that.

**Comment by daPhipz** [comment]
The only thing I could find is this (from the [GTK+ 3 Reference Manual](https://developer.gnome.org/gtk3/stable/GtkPopover.html)):

> By default, `GtkPopover` performs a GTK+ grab, in order to ensure input events get redirected to it while it is shown, and also so the popover is dismissed in the expected situations (clicks outside the popover, or the `Esc` key being pressed).
> If no such modal behavior is desired on a popover, `gtk_popover_set_modal()` may be called on it to tweak its behavior.

This doesn't get us very far, tbh :grimacing:
I think for the `icon-popover`, it should close on single-click when selecting an icon from the standard icon theme (the left tab). They are clearly visible without clicking and there isn't anything worth "previewing", like with a theme change.
The file chooser (right tab) closes when double-clicking a file and ignores double-clicks on folders, am I right? That's a good way of dealing with it, I think.

What's your take on this?

**Comment by Schneegans** [comment]
Since 45aac5edaa136dda2aae64626a33dd49224bcf49 and d7b73c75ea7d2254dc02356db22f919cff57c598, the `icon-select-popover` and the `application-select-popover` are hidden when one of their items is selected!
