### ISSUE TITLE
🌐 Translation workflow

### ISSUE THREAD

**Issue by daPhipz** [Schneegans/Fly-Pie#68]
**Continuation of the discussion from #65.**

My latest message over there:

> I think you missed the case in which both branches have new translations for different things.

Good catch! Yeah, this is a possible source of problems.

So, basically:
1. Add new features to `develop`, DO NOT touch `po` or `pot` whatsoever (apart from checking if translator comments are handled correctly, but then don't commit the file)
2. When you want to release a new version, you branch `develop` off to `translation` (name it whatever you want :wink:). While, theoretically, new features can still be merged into this branch, no new strings should be added (aka String Freeze).
3. Commit the result of `update-locales.sh` to `translation`
4. Notify translators to get work done
5. Merge `translation` into `master` and upload the translated release.
6. Merge `master` into `develop` to get the updated translations in the development version.

Illustration (the branch is called `release` here):
![Bildschirmfoto vom 2020-12-19 21-03-00](https://user-images.githubusercontent.com/30795174/102698511-2de01d80-423e-11eb-91ef-9fcdc7c3ae1b.png)

Am I getting this right?

> We could also consider removing the po/flypie.pot from the source tree as it can be auto-generated anyways.

When I understood your workflow suggestion above correctly, we could as well keep it and only update it on `translation`. This makes it easy and accessible to new translators who want to start a completely new language.

What do you think?

**Comment by Schneegans** [comment]
I think this is a good solution.

Do you want to add one sentence to https://github.com/Schneegans/Fly-Pie/blob/develop/docs/CONTRIBUTING.md#branching-guidelines accordingly? We should stick to the `release/vxxx` naming scheme as this is a de facto standard. And after all, its a good idea to implement bug fixes there as well. And it is inline with the linked video.

**Comment by daPhipz** [comment]
Ok! So there will be branches named `release/vX`, where `X` is the version number, am I right?

I have a small caveat with this solution:
Assume there is no release pending (no active `release/vX` branch). When a new translator comes on board now, they'll have no clean branch to merge the translations into - since all past `release` branches have been merged and closed.
This results in the same problem we were having: the translator would have to merge into `develop`. Or am I missing something here?

My proposal would be to have one _continuous_ `release` branch, which new translators could check out and work on.

**Comment by Schneegans** [comment]
This is true. But having a continuous `release` branch _feels somehow wrong_. Translators could base their work on `master` to have the same effect.

Maybe this could be a solution:
* We split the `update-locales.sh` into two file: `update-pot.sh` and `update-po.sh`.
* The latter accepts flag (jay!) deciding which locale to update (or all).
* I'll simply call the `update-pot.sh` once in a while in `develop`.
* Translators can then start from `develop`.
* They are only supposed to run `./update-po.sh <LANG CODE>`.

But we can do the thing with the short-living `release` branch anyways as this is a good point to call for translations updates.

What do you think?

**Comment by daPhipz** [comment]
Yes, I think this is a good idea. I'll start working on it, not sure if I have the time to finish it today, though.

**Comment by Schneegans** [comment]
At some point we could consider moving all scripts to a `scripts/` directory. :laughing:
