### ISSUE TITLE
Add architecture description

### ISSUE THREAD

**Issue by Schneegans** [Schneegans/Fly-Pie#78]
For contributors, it would be great to have at least some basic architecture description. This should contain information on:

- [ ] Why is the source code split into three directories?
- [ ] What is the data flow when a menu is opened?

**Comment by daPhipz** [comment]
I think when adding more documentation, we should also think about splitting up the README contents into smaller portions or provide some way of quickly navigating to the different sections, a Table of Contents for example. I'm sure there are scripts out there that can automatically create a ToC from a Markdown file. Will have a look!

Maybe put all docs about developing separate to what the end users need to know?

**Comment by Schneegans** [comment]
In another project I did it like this: https://github.com/cosmoscout/cosmoscout-vr/tree/develop/docs

I think I would use a similar approach for Fly-Pie. And yes, several parts of the README.md should be moved to the docs directory!

**Comment by daPhipz** [comment]
I love this approach!
Especially the links back to the ToC and to the next topic at the end of each page.
If you don't mind, I'll take care of splitting it all up 😊

**Comment by Schneegans** [comment]
I created a separate issue to keep things separate :smile:

**Comment by Schneegans** [comment]
I will start working on this issue here once #79 is resolved. Else we will run into quite some merge conflicts.
