### ISSUE TITLE
Super Key does not seem to count as a modifier key 

### ISSUE THREAD

**Issue by ykhurshid** [Schneegans/Fly-Pie#91]
Not sure if this should be considered a bug or feature request but considering that the super key is almost universally considered as a modifier key, I will lean on the former in this case.

As an example use case, I want to use Super+e to invoke a pie menu and I want turbo mode to be enabled as long as I hold down the super key.

**Comment by Schneegans** [comment]
Thank you for the report! Just to make sure that I understood you correctly: Binding menus to the Super key already works, but the turbo mode doesn't recognize it as a modifier key? I'll look into this!

**Comment by Schneegans** [comment]
I just pushed something to `develop` which may fix this. Can you test this on your end? The super key is always handled a bit special, for me it is actually called `MOD4` and not `SUPER`, so I am not sure if this is a universal fix or depends somehow on the system...

**Comment by ykhurshid** [comment]
Just tried the latest version now and turbo mode does indeed work as expected. Thanks a million!
