### ISSUE TITLE
Translations for Fly-Pie 5

### ISSUE THREAD

**Issue by Schneegans** [Schneegans/Fly-Pie#96]
Dear translators! Fly-Pie 5 is soon to be released and it would be great if you could update the translations!

I originally planned to include the achievements in this release, but there are so many changes already since the last version, that we shouldn't wait any longer. All the achievement & statistics related code is still in there but disabled for now. So please be not confused as there may be some string which you won't find in the user interface!

You can read the preliminary change log here: https://github.com/Schneegans/Fly-Pie/blob/release/v5/docs/changelog.md

- [x] German: @daPhipz 
- [ ] Italian: @albanobattistella 

You can follow the [translation guide](https://github.com/Schneegans/Fly-Pie/blob/develop/docs/translating.md) and should base your work on the [`release/v5`](https://github.com/Schneegans/Fly-Pie/tree/release/v5) branch.

Thank you so much!

**Comment by daPhipz** [comment]
Thanks for the notification!

I'm done with German, but before filing a PR, I would like to clarify some questions that came to my mind during the translation. I put them as comments in the code block below.
Here you go:

```
# Do you mean "Bronze"?
#: assets/settings.ui:273
msgid "🥉️ Copper Sponsors"
msgstr "🥉️ Kupfer-Unterstützer"

# Are there other support plans (higher amounts)?
# Should we convert the currency?
#: assets/settings.ui:342 src/prefs/MenuEditorPage.js:966
msgid ""
"💕️ Do you want to show that you love Fly-Pie? <a href=\"https://github.com/"
"sponsors/Schneegans\">Become a sponsor for as little as 1$ / month!</a>"
msgstr ""
"💕️ Möchten Sie zeigen, wie sehr Ihnen Fly-Pie gefällt? <a href=\"https://"
"github.com/sponsors/Schneegans\">Werden Sie ein Unterstützer - für nur $1 / "
"Monat!</a>"

# What is "it"?
# I assume you mean the Presets, that's why I'll go with "sie".
# Might be worth clarifying, though ;)
#: src/prefs/SettingsPage.js:327
msgid ""
"Here it will be deleted whenever Fly-Pie is updated. It has been saved "
"anyways, but please consider to store it in a safer place!"
msgstr ""
"Bei einem Update von Fly-Pie wird sie hier gelöscht. Sie wurde zwar "
"gespeichert, aber bitte ziehen Sie einen sicheren Ort in Betracht!"
```

I decided to post this here instead of including it in the file, in order to keep it clean.
What is your take on this? Thanks! :+1:

**Comment by Schneegans** [comment]
Thank you for this extremely quick response! If you have the time, you can also play around with the current state and check for any bugs! 

> Do you mean "Bronze"?

Yap :smiley: 

> Are there other support plans (higher amounts)?

Yes, there are 1$, 5$, and 10$ available. I reformulated that string to suggest that there are more options.

> Should we convert the currency?

I don't think so. GitHub just supports sponsoring in dollars, and the conversion changes daily...

> What is "it"?

You got it right, I added a comment accordingly!

Thank you very much!

**Comment by Schneegans** [comment]
@albanobattistella : Do you have all the required information to start working on this? I could also provide a step-by-step guide to make things easier if there are any difficulties!

**Comment by albanobattistella** [comment]
Hi Simon,

thanks,I'm working on...

Regards,

Albano

________________________________
Da: Simon Schneegans ***@***.***>
Inviato: giovedì 1 aprile 2021 08:12
A: Schneegans/Fly-Pie ***@***.***>
Cc: albanobattistella ***@***.***>; Mention ***@***.***>
Oggetto: Re: [Schneegans/Fly-Pie] Translations for Fly-Pie 5 (#96)


@albanobattistella<https://github.com/albanobattistella> : Do you have all the required information to start working on this? I could also provide a step-by-step guide to make things easier if there are any difficulties!
